.TH "fixfiles" "8" "2002031409" "" ""
.SH "ИМЯ"
fixfiles \- исправить SELinux-контексты безопасности файлов.

.SH "ОБЗОР"
.na

.B fixfiles
.I [\-v] [\-F] [\-f] relabel

.B fixfiles
.I [\-v] [\-F] { check | restore | verify } dir/file ...

.B fixfiles
.I [\-v] [\-F] [\-B | \-N time ] { check | restore | verify }

.B fixfiles 
.I [\-v] [\-F] \-R rpmpackagename[,rpmpackagename...] { check | restore | verify }

.B fixfiles
.I [\-v] [\-F] \-C PREVIOUS_FILECONTEXT  { check | restore | verify }

.B fixfiles
.I [-F] [-B] onboot

.ad

.SH "ОПИСАНИЕ"
На этой странице руководства приводится описание сценария
.BR fixfiles.
.P
Этот сценарий в основном используется для исправления базы данных контекстов безопасности (расширенных атрибутов) в файловых системах.  
.P
Его также можно запустить в любой момент, чтобы повторно проставить метки при добавлении поддержки новой политики или просто проверить, соответствуют ли контексты файлов ожиданиям пользователя. По умолчанию он повторно проставит метки во всех смонтированных файловых системах ext2, ext3, xfs и 
jfs, даже если у них нет параметра монтирования с контекстом безопасности. Флаг \-R позволяет использовать rpm-пакеты в качестве альтернативы.
Файл etc/selinux/fixfiles_exclude_dirs может содержать список каталогов, исключённых из повторного проставления меток.
.P
.B fixfiles onboot 
При следующей перезагрузке компьютера метки будет проставлены повторно.

.SH "ПАРАМЕТРЫ"
.TP 
.B \-B
При использовании с onboot сценарий fixfiles запишет текущую дату в файл /.autorelabel, чтобы потом её можно было использовать для ускорения проставления меток. При использовании с restore будут затронуты только те файлы, которые были изменены сегодня.
.TP
.B \-F
Принудительно сбросить контекст, чтобы он соответствовал file_context для настраиваемых файлов.

.TP 
.B \-f
Очистить каталог /tmp, не запрашивая подтверждение удаления у пользователя.

.TP 
.B \-R rpmpackagename[,rpmpackagename...]
Использовать базу данных rpm, чтобы найти все файлы в указанных пакетах и восстановить их контексты.
.TP
.B \-C PREVIOUS_FILECONTEXT
Выполнить diff, чтобы сравнить файл PREVIOUS_FILECONTEXT с текущим установленным файлом, и восстановить контекст всех затронутых файлов.

.TP 
.B \-N time
Применять изменения только к файлам, созданным после указанной даты. Дата должна быть указана в формате "ГГГГ\-ММ\-ДД ЧЧ:ММ". Поле даты будет передано в команду find \-\-newermt.

.TP
.B -v
Изменить уровень детализации с показа хода выполнения на показ подробных сведений. (Запуск restorecon с \-v вместо \-p.)

.SH "АРГУМЕНТЫ"
Одно из:
.TP 
.B check
Вывести все некорректные метки контекста файлов, показывая старый и новый контекст, но не изменяя его.
.TP 
.B restore
Изменить все некорректные метки контекста файлов.
.TP 
.B relabel
Запросить у пользователя подтверждение удаления содержимого каталога /tmp и затем изменить все некорректные метки контекста файлов, чтобы привести их в соответствие с файлом file_contexts.
.TP 
.B verify
Вывести список файлов с некорректными метками контекста, но не изменять их.
.TP 
.B [[dir/file] ... ] 
Список файлов или каталогов, для которых следует проверить контекст.

.SH "СМОТРИТЕ ТАКЖЕ"
.BR setfiles (8),
.BR restorecon (8)

.SH "АВТОРЫ"
Эта man-страница была написана Richard Hally <rhally@mindspring.com>.
Сценарий был написан Dan Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.

