#!/usr/bin/python3 -EsI
try:
    from subprocess import getstatusoutput
except ImportError:
    from commands import getstatusoutput
import sys
rc = [-1, '']
try:
    rc = getstatusoutput(sys.argv[1])
except:
    pass
if rc[0] == 0:
    print(rc[1])
