.TH "failsafe_context" "5" "28 ноября 2011" "Security Enhanced Linux" "Конфигурация SELinux"
.SH "ИМЯ"
failsafe_context \- файл конфигурации резервного контекста SELinux
.
.SH "ОПИСАНИЕ"
Файл
.I failsafe_context
позволяет поддерживающим SELinux приложениям, таким как
.BR PAM "(8), "
получать известный действительный контекст входа для администратора, если в других расположениях отсутствуют действительные записи по умолчанию.
.sp
.BR selinux_failsafe_context_path "(3) "
возвращает путь активной политики к этому файлу. Файл резервного контекста по умолчанию:
.RS
.I /etc/selinux/{SELINUXTYPE}/contexts/failsafe_context
.RE
.sp
Где \fI{SELINUXTYPE}\fR - запись из файла конфигурации selinux \fIconfig\fR (см. \fBselinux_config\fR(5)).
.sp
Следующие функции выполняют чтение этого файла по пути активной политики, если им не удаётся получить контекст по умолчанию:
.br
.RS
.BR get_default_context "(3) "
.br
.BR get_ordered_context_list "(3) "
.br
.BR get_ordered_context_list_with_level "(3) "
.br
.BR get_default_context_with_level "(3) "
.br
.BR get_default_context_with_role "(3) "
.br
.BR get_default_context_with_rolelevel "(3) "
.br
.BR query_user_context "(3) "
.br
.BR manual_user_enter_context "(3) "
.RE
.
.SH "ФОРМАТ ФАЙЛА"
Файл состоит из следующей однострочной записи:
.RS
\fIrole\fB:\fItype\fR[\fB:\fIrange\fR]
.RE
.sp
Где:
.RS
.I role
.I type
.I range
.RS
Роль, тип и необязательный диапазон (для MCS/MLS), разделённые двоеточиями (:), которые формируют действительный контекст процесса входа для получения администратором доступа к системе.
.RE
.RE
.
.SH "ПРИМЕР"
# ./contexts/failsafe_context
.br
unconfined_r:unconfined_t:s0
.
.SH "СМОТРИТЕ ТАКЖЕ"
.ad l
.nh
.BR selinux "(8), " selinux_failsafe_context_path "(3), " PAM "(8), " selinux_default_type_path "(3), " get_default_context "(3), " get_ordered_context_list "(3), " get_ordered_context_list_with_level "(3), " get_default_context_with_level "(3), " get_default_context_with_role "(3), " get_default_context_with_rolelevel "(3), " query_user_context "(3), " manual_user_enter_context "(3), " selinux_config "(5) "


.SH АВТОРЫ
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
