.TH "virtual_image_context" "5" "28 ноября 2011" "Security Enhanced Linux" "Конфигурация SELinux"
.SH "ИМЯ"
virtual_image_context \- файл конфигурации SELinux-контекста образа виртуальной машины
.
.SH "ОПИСАНИЕ"
Файл
.I virtual_image_context
содержит список контекстов образов для использования поддерживающим SELinux API виртуализации libvirt (см. \fBlibvirtd\fR(8)).
.sp
.BR selinux_virtual_image_context_path "(3) "
вернёт путь активной политики к этому файлу. Файл контекстов виртуальных образов по умолчанию:
.RS
.I /etc/selinux/{SELINUXTYPE}/contexts/virtual_image_context
.RE
.sp
Где \fI{SELINUXTYPE}\fR - запись из файла конфигурации selinux \fIconfig\fR (см. \fBselinux_config\fR(5)).
.
.SH "ФОРМАТ ФАЙЛА"
Каждая строка в файле состоит из записи следующего вида:
.RS
.IB user : role : type \fR[\fB:\fIrange\fR]
.RE
.sp
Где:
.RS
.I user role type range
.RS
Пользователь, роль, тип и необязательный диапазон (для MCS/MLS), разделённые двоеточиями (:), которые могут использоваться в качестве контекста виртуального образа.
.RE
.RE
.
.SH "ПРИМЕР"
# ./contexts/virtual_image_context
.br
system_u:object_r:svirt_image_t:s0
.br
system_u:object_r:svirt_content_t:s0
.
.SH "СМОТРИТЕ ТАКЖЕ"
.ad l
.nh
.BR selinux "(8), " libvirtd "(8), " selinux_virtual_image_context_path "(3), " selinux_config "(5) "


.SH АВТОРЫ
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
