.TH "freecon" "3" "1 January 2004" "russell@coker.com.au" "SE Linux API documentation"
.SH "NAME"
freecon, freeconary \- free memory associated with SELinux security contexts.
.SH "SYNOPSIS"
.B #include <selinux/selinux.h>
.sp
.BI "void freecon(security_context_t "con );
.br 
.BI "void freeconary(security_context_t *" con );

.SH "DESCRIPTION"
.B freecon
frees the memory allocated for a security context.

.B freeconary
frees the memory allocated for a context array.

.SH "SEE ALSO"
.BR selinux "(8)"

