.TH "is_selinux_enabled" "3" "1 January 2004" "russell@coker.com.au" "SE Linux API documentation"
.SH "NAME"
is_selinux_enabled \- check whether SELinux is enabled
.SH "SYNOPSIS"
.B #include <selinux/selinux.h>
.sp
.B int is_selinux_enabled();

.SH "DESCRIPTION"
.B is_selinux_enabled
returns 1 if SE Linux is running or 0 if it is not.  May change soon.

.SH "SEE ALSO"
.BR selinux "(8)"

