.TH "security_check_context" "3" "1 January 2004" "russell@coker.com.au" "SELinux API documentation"
.SH "NAME"
security_check_context \- check the validity of a SELinux context
.SH "SYNOPSIS"
.B #include <selinux/selinux.h>
.sp
.BI "int security_check_context(security_context_t "con );

.SH "DESCRIPTION"
.B security_check_context
returns 0 if SELinux is running and the context is valid, otherwise it
returns -1.

.SH "SEE ALSO"
.BR selinux "(8)"

