.TH "security_load_policy" "3" "1 January 2004" "russell@coker.com.au" "SE Linux API documentation"
.SH "NAME"
security_load_policy \- load a new SELinux policy
.SH "SYNOPSIS"
.B #include <selinux/selinux.h>
.sp
.BI "int security_load_policy(void *" data ", size_t "len );

.SH "DESCRIPTION"
.B security_load_policy
loads a new policy, returns 0 for success and -1 for error.

.SH "SEE ALSO"
.BR selinux "(8)"

