.TH CHCAT "8" "Сентябрь 2005" "chcat" "Команды пользователя"
.SH ИМЯ
chcat \- изменить SELinux-категорию безопасности файла
.SH ОБЗОР
.B chcat
\fIcategory file\fR...
.br
.B chcat -l 
\fIcategory user\fR...
.br
.B chcat
\fI[[+|-]category...]  file\fR...
.br
.B chcat -l 
\fI[[+|-]category...]  user\fR...
.br
.B chcat
[\fI-d\fR] \fIfile\fR...
.br
.B chcat -l 
[\fI-d\fR] \fIuser\fR...
.br
.B chcat
\fI-L\fR [ \-l ] [ user ... ]
.br
.SH ОПИСАНИЕ
.PP
Изменить/Удалить категорию безопасности \fIcategory\fR для каждого файла \fIfile\fR или пользователя \fIuser\fR.
.PP
Используйте +/- для добавления/удаления категорий из \fIfile\fR или \fIuser\fR.
.PP
.B
Примечание:
При удалении категории необходимо указать '\-\-' в командной строке перед использованием синтаксиса \-Category. Это сообщает команде, что вы закончили вводить параметры и теперь указываете имя категории.

.TP
\fB\-d\fR
удалить категорию из каждого FILE/USER.
.TP
\fB\-L\fR
вывести список доступных категорий.
.TP
\fB\-l\fR
если используется, chcat будет работать с пользователями, а не с файлами.
.SH "СМОТРИТЕ ТАКЖЕ"
.TP
chcon(1), selinux(8), semanage(8)
.PP
.br
При работе с файлами этот сценарий вызывает команду chcon.
.SH "FILES"
/etc/selinux/{SELINUXTYPE}/setrans.conf 
.br
/etc/selinux/{SELINUXTYPE}/seusers

.SH "АВТОРЫ"
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>
