.TH  "mcs"  "8"  "8 сентября 2005" "dwalsh@redhat.com" "Документация по MCS"

.SH "ИМЯ"
mcs \- мультикатегорийная система

.SH "ОПИСАНИЕ"
MCS (мультикатегорийная система) позволяет пользователям проставлять в своей системе метки для файлов внутри определённых администратором категорий. Затем эта система использует принудительное управление доступом SELinux, чтобы защитить эти файлы. MCS - дискреционная модель, которая позволяет пользователям отмечать свои данные дополнительными тегами, накладывая дальнейшие ограничения доступа. Обязательным является только один аспект - авторизовывать пользователей для категорий, определяя их уровень допуска в политике. MCS похожа на MLS, выполняет те же самые пути кода и использует ту же самую инфраструктуру поддержки. Они отличаются между собой только спецификой настройки.


Файл конфигурации
.I /etc/selinux/{SELINUXTYPE}/setrans.conf
преобразовывает метки на диске в удобную для прочтения человеком форму. В этом файле администраторы могут определить любые необходимые метки.
Некоторые приложения, такие как вывод на экран и аудит, будут использовать эти метки для идентификации файлов. Если для файла будет задана категория, другие приложения/службы не получат к нему доступ.
.P
Примеры меток файлов: PatientRecord, CompanyConfidential и так далее.

.SH "СМОТРИТЕ ТАКЖЕ"
selinux(8), chcon(1)

.SH ФАЙЛЫ
/etc/selinux/{SELINUXTYPE}/setrans.conf 

.SH АВТОРЫ
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>
