.TH "mcstransd" "8" "16 октября 2009" "dwalsh@redhat.com" "Документация по MCS"
.SH "ИМЯ"
mcstransd \- внутренняя служба MCS (мультикатегорийная система). Переводит метки MCS/MLS SELinux в удобную для прочтения человеком форму.

.SH "ОБЗОР"
.B mcstransd [-f] [-h]
.P

.SH "ОПИСАНИЕ"
Эта страница руководства содержит описание программы
.BR mcstransd.
.P
Эта внутренняя служба выполняет чтение файла конфигурации /etc/selinux/{SELINUXTYPE}/setrans.conf и связывается с libselinux через сокет в /var/run/setrans.
.SH "ПАРАМЕТРЫ"
.TP
\-f
Запустить mcstransd на переднем плане. Не запускать как внутреннюю службу.
.TP
\-h
Вывести краткое описание доступных параметров командной строки\&.

.SH "ФАЙЛЫ"
/etc/selinux/{SELINUXTYPE}/setrans.conf 

.SH "СМОТРИТЕ ТАКЖЕ"
.BR setrans.conf (5), mcs (8)

.SH "АВТОРЫ"
Эта man-страница написана Dan Walsh <dwalsh@redhat.com>.
Исходная версия программы написана Dan Walsh <dwalsh@redhat.com>.
Программа улучшена/переписана Joe Nall <joe@nall.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
