# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _selinux
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


is_selinux_enabled = _selinux.is_selinux_enabled
is_selinux_mls_enabled = _selinux.is_selinux_mls_enabled
getcon = _selinux.getcon
getcon_raw = _selinux.getcon_raw
setcon = _selinux.setcon
setcon_raw = _selinux.setcon_raw
getpidcon = _selinux.getpidcon
getpidcon_raw = _selinux.getpidcon_raw
getprevcon = _selinux.getprevcon
getprevcon_raw = _selinux.getprevcon_raw
getexeccon = _selinux.getexeccon
getexeccon_raw = _selinux.getexeccon_raw
setexeccon = _selinux.setexeccon
setexeccon_raw = _selinux.setexeccon_raw
getfscreatecon = _selinux.getfscreatecon
getfscreatecon_raw = _selinux.getfscreatecon_raw
setfscreatecon = _selinux.setfscreatecon
setfscreatecon_raw = _selinux.setfscreatecon_raw
getkeycreatecon = _selinux.getkeycreatecon
getkeycreatecon_raw = _selinux.getkeycreatecon_raw
setkeycreatecon = _selinux.setkeycreatecon
setkeycreatecon_raw = _selinux.setkeycreatecon_raw
getsockcreatecon = _selinux.getsockcreatecon
getsockcreatecon_raw = _selinux.getsockcreatecon_raw
setsockcreatecon = _selinux.setsockcreatecon
setsockcreatecon_raw = _selinux.setsockcreatecon_raw
getfilecon = _selinux.getfilecon
getfilecon_raw = _selinux.getfilecon_raw
lgetfilecon = _selinux.lgetfilecon
lgetfilecon_raw = _selinux.lgetfilecon_raw
fgetfilecon = _selinux.fgetfilecon
fgetfilecon_raw = _selinux.fgetfilecon_raw
setfilecon = _selinux.setfilecon
setfilecon_raw = _selinux.setfilecon_raw
lsetfilecon = _selinux.lsetfilecon
lsetfilecon_raw = _selinux.lsetfilecon_raw
fsetfilecon = _selinux.fsetfilecon
fsetfilecon_raw = _selinux.fsetfilecon_raw
getpeercon = _selinux.getpeercon
getpeercon_raw = _selinux.getpeercon_raw
class av_decision(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, av_decision, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, av_decision, name)
    __repr__ = _swig_repr
    __swig_setmethods__["allowed"] = _selinux.av_decision_allowed_set
    __swig_getmethods__["allowed"] = _selinux.av_decision_allowed_get
    if _newclass:allowed = _swig_property(_selinux.av_decision_allowed_get, _selinux.av_decision_allowed_set)
    __swig_setmethods__["decided"] = _selinux.av_decision_decided_set
    __swig_getmethods__["decided"] = _selinux.av_decision_decided_get
    if _newclass:decided = _swig_property(_selinux.av_decision_decided_get, _selinux.av_decision_decided_set)
    __swig_setmethods__["auditallow"] = _selinux.av_decision_auditallow_set
    __swig_getmethods__["auditallow"] = _selinux.av_decision_auditallow_get
    if _newclass:auditallow = _swig_property(_selinux.av_decision_auditallow_get, _selinux.av_decision_auditallow_set)
    __swig_setmethods__["auditdeny"] = _selinux.av_decision_auditdeny_set
    __swig_getmethods__["auditdeny"] = _selinux.av_decision_auditdeny_get
    if _newclass:auditdeny = _swig_property(_selinux.av_decision_auditdeny_get, _selinux.av_decision_auditdeny_set)
    __swig_setmethods__["seqno"] = _selinux.av_decision_seqno_set
    __swig_getmethods__["seqno"] = _selinux.av_decision_seqno_get
    if _newclass:seqno = _swig_property(_selinux.av_decision_seqno_get, _selinux.av_decision_seqno_set)
    def __init__(self, *args): 
        this = _selinux.new_av_decision(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _selinux.delete_av_decision
    __del__ = lambda self : None;
av_decision_swigregister = _selinux.av_decision_swigregister
av_decision_swigregister(av_decision)

security_compute_av = _selinux.security_compute_av
security_compute_av_raw = _selinux.security_compute_av_raw
security_compute_create = _selinux.security_compute_create
security_compute_create_raw = _selinux.security_compute_create_raw
security_compute_relabel = _selinux.security_compute_relabel
security_compute_relabel_raw = _selinux.security_compute_relabel_raw
security_compute_member = _selinux.security_compute_member
security_compute_member_raw = _selinux.security_compute_member_raw
security_compute_user = _selinux.security_compute_user
security_compute_user_raw = _selinux.security_compute_user_raw
security_load_policy = _selinux.security_load_policy
selinux_mkload_policy = _selinux.selinux_mkload_policy
selinux_init_load_policy = _selinux.selinux_init_load_policy
class SELboolean(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SELboolean, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SELboolean, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _selinux.SELboolean_name_set
    __swig_getmethods__["name"] = _selinux.SELboolean_name_get
    if _newclass:name = _swig_property(_selinux.SELboolean_name_get, _selinux.SELboolean_name_set)
    __swig_setmethods__["value"] = _selinux.SELboolean_value_set
    __swig_getmethods__["value"] = _selinux.SELboolean_value_get
    if _newclass:value = _swig_property(_selinux.SELboolean_value_get, _selinux.SELboolean_value_set)
    def __init__(self, *args): 
        this = _selinux.new_SELboolean(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _selinux.delete_SELboolean
    __del__ = lambda self : None;
SELboolean_swigregister = _selinux.SELboolean_swigregister
SELboolean_swigregister(SELboolean)

security_set_boolean_list = _selinux.security_set_boolean_list
security_load_booleans = _selinux.security_load_booleans
security_check_context = _selinux.security_check_context
security_check_context_raw = _selinux.security_check_context_raw
security_canonicalize_context = _selinux.security_canonicalize_context
security_canonicalize_context_raw = _selinux.security_canonicalize_context_raw
security_getenforce = _selinux.security_getenforce
security_setenforce = _selinux.security_setenforce
security_disable = _selinux.security_disable
security_policyvers = _selinux.security_policyvers
security_get_boolean_names = _selinux.security_get_boolean_names
security_get_boolean_pending = _selinux.security_get_boolean_pending
security_get_boolean_active = _selinux.security_get_boolean_active
security_set_boolean = _selinux.security_set_boolean
security_commit_booleans = _selinux.security_commit_booleans
string_to_security_class = _selinux.string_to_security_class
string_to_av_perm = _selinux.string_to_av_perm
print_access_vector = _selinux.print_access_vector
MATCHPATHCON_BASEONLY = _selinux.MATCHPATHCON_BASEONLY
MATCHPATHCON_NOTRANS = _selinux.MATCHPATHCON_NOTRANS
MATCHPATHCON_VALIDATE = _selinux.MATCHPATHCON_VALIDATE
set_matchpathcon_flags = _selinux.set_matchpathcon_flags
matchpathcon_init = _selinux.matchpathcon_init
matchpathcon_init_prefix = _selinux.matchpathcon_init_prefix
matchpathcon_fini = _selinux.matchpathcon_fini
matchpathcon = _selinux.matchpathcon
matchpathcon_index = _selinux.matchpathcon_index
matchpathcon_filespec_add = _selinux.matchpathcon_filespec_add
matchpathcon_filespec_destroy = _selinux.matchpathcon_filespec_destroy
matchpathcon_filespec_eval = _selinux.matchpathcon_filespec_eval
matchpathcon_checkmatches = _selinux.matchpathcon_checkmatches
matchmediacon = _selinux.matchmediacon
selinux_getenforcemode = _selinux.selinux_getenforcemode
selinux_getpolicytype = _selinux.selinux_getpolicytype
selinux_policy_root = _selinux.selinux_policy_root
selinux_binary_policy_path = _selinux.selinux_binary_policy_path
selinux_failsafe_context_path = _selinux.selinux_failsafe_context_path
selinux_removable_context_path = _selinux.selinux_removable_context_path
selinux_default_context_path = _selinux.selinux_default_context_path
selinux_user_contexts_path = _selinux.selinux_user_contexts_path
selinux_file_context_path = _selinux.selinux_file_context_path
selinux_file_context_homedir_path = _selinux.selinux_file_context_homedir_path
selinux_file_context_local_path = _selinux.selinux_file_context_local_path
selinux_homedir_context_path = _selinux.selinux_homedir_context_path
selinux_media_context_path = _selinux.selinux_media_context_path
selinux_contexts_path = _selinux.selinux_contexts_path
selinux_securetty_types_path = _selinux.selinux_securetty_types_path
selinux_booleans_path = _selinux.selinux_booleans_path
selinux_customizable_types_path = _selinux.selinux_customizable_types_path
selinux_users_path = _selinux.selinux_users_path
selinux_usersconf_path = _selinux.selinux_usersconf_path
selinux_translations_path = _selinux.selinux_translations_path
selinux_netfilter_context_path = _selinux.selinux_netfilter_context_path
selinux_path = _selinux.selinux_path
selinux_check_passwd_access = _selinux.selinux_check_passwd_access
checkPasswdAccess = _selinux.checkPasswdAccess
selinux_check_securetty_context = _selinux.selinux_check_securetty_context
set_selinuxmnt = _selinux.set_selinuxmnt
rpm_execcon = _selinux.rpm_execcon
is_context_customizable = _selinux.is_context_customizable
selinux_trans_to_raw_context = _selinux.selinux_trans_to_raw_context
selinux_raw_to_trans_context = _selinux.selinux_raw_to_trans_context
getseuserbyname = _selinux.getseuserbyname
selinux_file_context_cmp = _selinux.selinux_file_context_cmp
selinux_file_context_verify = _selinux.selinux_file_context_verify
selinux_lsetfilecon_default = _selinux.selinux_lsetfilecon_default
selinux_default_type_path = _selinux.selinux_default_type_path
get_default_type = _selinux.get_default_type
SELINUX_DEFAULTUSER = _selinux.SELINUX_DEFAULTUSER
get_ordered_context_list = _selinux.get_ordered_context_list
get_ordered_context_list_with_level = _selinux.get_ordered_context_list_with_level
get_default_context = _selinux.get_default_context
get_default_context_with_level = _selinux.get_default_context_with_level
get_default_context_with_role = _selinux.get_default_context_with_role
get_default_context_with_rolelevel = _selinux.get_default_context_with_rolelevel
query_user_context = _selinux.query_user_context
manual_user_enter_context = _selinux.manual_user_enter_context


