.TH "sestatus.conf" "5" "26 ноября 2011" "Security Enhanced Linux" "Файл конфигурации sestatus"

.SH "ИМЯ"
sestatus.conf \- файл конфигурации \fBsestatus\fR(8).

.SH "ОПИСАНИЕ"
Файл \fIsestatus.conf\fR используется командой \fBsestatus\fR(8) с параметром \fB\-v\fR, чтобы определить, какие контексты безопасности файлов и процессов следует показать.
.sp
Полный путь к файлу конфигурации:
.RS
\fI/etc/sestatus.conf\fR
.RE
.RE
.sp
Файл состоит из двух необязательных разделов (описание содержится в разделе \fBФОРМАТ ФАЙЛА\fR). Независимо от того, существуют ли эти разделы, всегда показывается следующее:
.RS
Контекст текущего процесса
.br
Контекст процесса init 
.br
Контекст файла управляющего терминала
.RE

.SH "ФОРМАТ ФАЙЛА"
Формат состоит из двух необязательных разделов (пример далее):
.RS
.B [files]
.br
.I file_name
.br
.I [file_name]
.br
.I ...
.sp
.B [process]
.br
.I executable_file_name
.br
.I [executable_file_name]
.br
.I ...
.RE
.sp
Где:
.RS
.B [files]
.RS
Начало блока списка файлов.
.RE
.I file_name
.RS
Одно или несколько полных имён файлов (каждое на новой строке), контекст которых будет показан. Если файл не существует, он игнорируется. Если файл является символической ссылкой, \fBsestatus \-v\fR также покажет контекст целевого файла.
.RE
.sp
.B [process]
.RS
Начало блока списка процессов.
.RE
.I executable_file_name
.RS
Одно или несколько полных имён исполняемых файлов; будет показан контекст соответствующих активных процессов. Каждая запись находится на новой строке.
.RE
.RE

.SH "ПРИМЕР"
# /etc/sestatus.conf
.br
[files]
.br
/etc/passwd
.br
/etc/shadow
.br
/bin/bash
.br
/bin/login
.br
/lib/libc.so.6
.br
/lib/ld-linux.so.2
.br
/lib/ld.so.1
.sp
[process]
.br
/sbin/mingetty
.br
/sbin/agetty
.br
/usr/sbin/sshd
.RE

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux "(8), " sestatus "(8) "

.SH "СМОТРИТЕ ТАКЖЕ"
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>
