.TH "sestatus" "8" "26 ноября 2011" "Security Enhanced Linux" "Документация по командной строке SELinux"
.SH "ИМЯ"
sestatus \- утилита для просмотра состояния SELinux

.SH "ОБЗОР"
.B sestatus
.I [\-v] [\-b]  
.P
Эта утилита используется для получения состояния системы, в которой работает SELinux.

.SH "ОПИСАНИЕ"
Эта страница руководства содержит описание программы
.BR sestatus.
.sp
Эта утилита используется для получения состояния системы, в которой работает SELinux. Она показывает сведения о том, включён или отключён SELinux, расположение ключевых каталогов, а также загруженную политику и её состояние. Пример:
.RS
> sestatus
.br
SELinux status:              enabled
.br
SELinuxfs mount:             /selinux
.br
SELinux root directory:      /etc/selinux
.br
Loaded policy name:          targeted
.br
Current mode:                permissive
.br
Mode from config file:       enforcing
.br
Policy MLS status:           enabled
.br
Policy deny_unknown status:  allow
.br
Memory protection checking:  actual (secure)
.br
Max kernel policy version:   26
.RE
.sp
\fBsestatus\fR также можно использовать, чтобы просмотреть:
.RS
.IP "-" 4
Контексты безопасности файлов и процессов, перечисленные в файле \fI/etc/sestatus.conf\fR. Описание формата этого файла содержится в \fBsestatus.conf\fR(5).
.IP "-" 4
Состояние логических переключателей.
.RE

.SH "ПАРАМЕТРЫ"
.B \-v
.RS
Показать контексты файлов и процессов, перечисленные в файле \fI/etc/sestatus.conf\fR. Также проверяет, является ли файл символической ссылкой (если является, то также будет показан контекст целевого файла).
.sp
Всегда будут показаны следующие контексты:
.RS
Контекст текущего процесса
.br
Контекст процесса init 
.br
Контекст файла управляющего терминала
.RE
.RE
.sp
.B \-b
.RS
Показать текущее состояние логических переключателей.
.RE

.SH "ФАЙЛЫ"
.I /etc/sestatus.conf

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux "(8), " sestatus.conf "(5)

.SH "АВТОРЫ"
Эта страница руководства была написана Daniel Walsh <dwalsh@redhat.com>.
.br
Программа была написана Chris PeBenito <pebenito@gentoo.org>.
.br
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
