.TH "restorecond" "8" "2002031409" "" ""
.SH "ИМЯ"
restorecond \- внутренняя служба, которая отслеживает создание файлов и затем задаёт для них SELinux-контекст по умолчанию

.SH "ОБЗОР"
.B restorecond  [\-d] [-h] [\-f restorecond_file ] [\-u] [\-v]
.P

.SH "ОПИСАНИЕ"
Эта страница руководства содержит описание программы
.BR restorecond.
.P
Эта внутренняя служба использует inotify для отслеживания файлов, перечисленных в /etc/selinux/restorecond.conf. После создания этих файлов эта служба обеспечивает присвоение им правильного контекста, связанного с политикой.

.SH "ПАРАМЕТРЫ"
.TP 
.B \-d
Включить режим отладки. Приложение останется на переднем плане, будет показано много отладочных сообщений.
.TP
. B \-h
Вывести сведения об использовании.
.TP
.B \-f restorecond_file
Использовать альтернативный файл restorecond.conf.
.TP
.B \-u
Включить пользовательский режим. Запускает restorecond в сеансе пользователя и выполняет чтение /etc/selinux/restorecond_user.conf. Использует dbus, чтобы удостовериться, что в одном сеансе пользователя запущен только один экземпляр restorecond.
.TP
.B \-v
Включить отладку с подробным выводом. (Сообщать об отсутствующих файлах)

.SH "ФАЙЛЫ"
/etc/selinux/restorecond.conf
/etc/selinux/restorecond_user.conf

.SH "СМОТРИТЕ ТАКЖЕ"
.BR restorecon (8)

.SH "АВТОРЫ"
Эта man-страница и программа были написаны Dan Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
