.TH "restorecon_xattr" "8" "24 сентября 2016" "" "Команда пользователя SELinux"
.SH "ИМЯ"
restorecon_xattr \- управление записями расширенных атрибутов
.I security.restorecon_last,
добавленными с помощью
.BR setfiles (8)
или
.BR restorecon (8).

.SH "ОБЗОР"
.B restorecon_xattr
.RB [ \-d ]
.RB [ \-D ]
.RB [ \-m ]
.RB [ \-n ]
.RB [ \-r ]
.RB [ \-v ]
.RB [ \-e
.IR directory ]
.RB [ \-f
.IR specfile ]
.I pathname

.SH "ОПИСАНИЕ"
.B restorecon_xattr
покажет дайджесты SHA1, добавленные в расширенные атрибуты
.I security.restorecon_last,
или полностью удалит эти атрибуты. Эти атрибуты устанавливаются командой
.BR restorecon (8)
или
.BR setfiles (8)
для указанных каталогов при рекурсивном повторном проставлении меток.
.sp
.B restorecon_xattr
полезно использовать для управления записями расширенных атрибутов, в частности, когда пользователи забывают, из каких каталогов они запускали
.BR restorecon (8)
или
.BR setfiles (8).
.sp
Файловые системы
.B RAMFS
и
.B TMPFS
не поддерживают расширенные атрибуты
.I security.restorecon_last
и автоматически исключаются из поиска.
.sp
По умолчанию
.B restorecon_xattr
показывает дайджесты SHA1, добавляя в конце "Match", если они соответствуют установленному по умолчанию файлу спецификации или файлу спецификации
.I specfile,
который установлен с помощью параметра
.B \-f.
Несоответствующие дайджесты SHA1 будут показаны с добавлением "No Match" в конце.
Эту возможность можно отключить с помощью параметра
.B \-n.

.SH "ПАРАМЕТРЫ"
.TP
.B \-d
удалить все несоответствующие записи дайджеста каталога
.I security.restorecon_last.
.TP
.B \-D
удалить все записи дайджеста каталога
.I security.restorecon_last.
.TP
.B \-m
не выполнять чтение
.B /proc/mounts
для получения списка монтирований без seclabel, которые следует исключить из проверок с повторным проставлением меток.
.br
установка параметра
.B \-m
полезна при наличии смонтированной файловой системы без seclabel, в которой в расположенном ниже каталоге смонтирована файловая система с seclabel.
.TP
.B \-n
не добавлять "Match" или "No Match" в конце отображаемых дайджестов.
.TP
.B \-r
рекурсивно спускаться по каталогам.
.TP
.B \-v
показать дайджест SHA1, созданный установленным файлом спецификации.
.TP
.B \-e
.I directory
.br
каталог, который следует исключить (чтобы исключить более одного каталога, этот параметр необходимо использовать соответствующее количество раз).
.TP
.B \-f
.I specfile
.br
необязательный файл спецификации
.I specfile,
который содержит записи контекстов файлов в соответствии с описанием в
.BR file_contexts (5).
Он будет использоваться
.BR selabel_open (3)
для получения набора записей меток; получение дайджеста SHA1 выполняется с помощью
.BR selabel_digest (3).
Если этот параметр не указан, будет использоваться файл file_contexts по умолчанию.

.SH "АРГУМЕНТЫ"
.TP
.I pathname
.br
путь к дереву каталогов, в котором следует выполнить поиск.

.SH "СМОТРИТЕ ТАКЖЕ"
.BR restorecon (8),
.BR setfiles (8)

.SH "АВТОРЫ"
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>
