.TH "semanage-dontaudit" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-dontaudit \- утилита dontaudit для управления политикой SELinux
.SH "ОБЗОР"
.B semanage dontaudit [\-h] [\-S STORE] [\-N] {on,off}

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage dontaudit определяет, будут ли правила dontaudit присутствовать в политике. Авторы политик применяют правила dontaudit для того, чтобы ограниченные приложения использовали альтернативные пути. При использовании правил dontaudit отказы в доступе выполняются, но не журналируются. Иногда использование правил dontaudit вызывает ошибки в приложениях (но авторы политик не знают о них, так как аудит кэша вектора доступа не выполняется). Отключите правила dontaudit с помощью этой команды, чтобы проверить, блокирует ли ядро доступ.

.SH "ПАРАМЕТРЫ"
.TP
.I   \-h, \-\-help
Показать это справочное сообщение и выйти
.TP
.I   \-S STORE, \-\-store STORE
Выбрать для управления альтернативное хранилище политики SELinux
.TP
.I   \-N, \-\-noreload
Не перезагружать политику после фиксации

.SH ПРИМЕР
.nf
Отключить правила dontaudit
# semanage dontaudit off

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
