.TH "semanage-boolean" "8" "20130617" "" ""
.SH "ИМЯ"
semanage\-boolean \- утилита для управления политикой SELinux, основанная на использовании логических переключателей
.SH "ОБЗОР"
.B semanage boolean [\-h] [\-n] [\-N] [\-S STORE] [  \-\-extract  | \-\-deleteall  | \-\-list [\-C] | \-\-modify ( \-\-on | \-\-off ) boolean  ]

.SH "ОПИСАНИЕ"
Команда semanage используется для настройки определённых элементов политики
SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage boolean управляет настройками логических переключателей в политике SELinux. Логические переключатели - это правила if\-then\-else, записанные в политике SELinux. Их можно использовать для настройки того, как правила политики SELinux влияют на ограниченный домен.
.SH "ПАРАМЕТРЫ"
.TP
.I  \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта 
.TP
.I  \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I  \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I  \-C, \-\-locallist
вывести список локальных настроек
.TP
.I  \-m, \-\-modify
изменить запись указанного типа объекта
.TP
.I  \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I  \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I  \-D, \-\-deleteall
удалить все локальные настройки
.TP
.I  \-1, \-\-on
включить логический переключатель
.TP
.I  \-0, \-\-off
отключить логический переключатель
.SH ПРИМЕР
.nf
Включить на apache логический переключатель can send mail
# semanage boolean \-m \-\-on httpd_can_sendmail

Вывести список настраиваемых логических переключателей
# semanage boolean \-l \-C

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8),
.BR setsebool (8),
.BR getsebool (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
