.TH "semanage-login" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-login \- утилита для управления политикой SELinux, предназначенная для сопоставления пользователей Linux с пользователями SELinux
.SH "ОБЗОР"
.B semanage login [\-h] [\-n] [\-N] [\-S STORE] [ \-\-add \-s SEUSER \-r RANGE LOGIN | \-\-delete LOGIN | \-\-deleteall  | \-\-extract  | \-\-list [\-C] | \-\-modify \-s SEUSER \-r RANGE LOGIN ]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage login управляет сопоставлением пользователей Linux с пользователями SELinux. Её можно использовать для включения ограниченных пользователей. Например, можно определить, что конкретный пользователь или группа пользователей будет входить в систему как пользователь user_u. Чтобы указать имя группы, поставьте перед ним знак '%'.

.SH "ПАРАМЕТРЫ"
.TP
.I  \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I  \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I  \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I  \-C, \-\-locallist
вывести список локальных настроек
.TP
.I  \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I  \-a, \-\-add
добавить запись указанного типа объекта
.TP
.I  \-d, \-\-delete
удалить запись указанного типа объекта
.TP
.I \-m, \-\-modify
изменить запись указанного типа объекта
.TP
.I  \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I  \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I  \-D, \-\-deleteall
удалить все локальные настройки
.TP
.I  \-s SEUSER, \-\-seuser SEUSER
имя пользователя SELinux
.TP
.I  \-r RANGE, \-\-range RANGE
диапазон безопасности MLS/MCS (только для систем с поддержкой MLS/MCS). По умолчанию SELinux-диапазон для сопоставления имени входа SELinux принимает значение диапазона записи пользователя SELinux. По умолчанию SELinux-диапазон для пользователя SELinux принимает значение s0.

.SH ПРИМЕР
.nf
Изменить пользователя по умолчанию в системе на пользователя guest_u
# semanage login \-m \-s guest_u __default__
Назначить пользователю gijoe на компьютере с поддержкой MLS диапазон и пользователя staff_u
# semanage login \-a \-s staff_u \-rSystemLow-Secret gijoe
Назначить всем пользователям в группе engineering пользователя staff_u
# semanage login \-a \-s staff_u %engineering

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8),
.BR semanage-user (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
