.TH "semanage-module" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-module \- утилита для управления политикой SELinux, предназначенная для сопоставления модулей 
.SH "ОБЗОР"
.B semanage module [\-h] [\-n] [\-N] [\-S STORE] (\-a | \-r | \-e | \-d | \-\-extract | \-\-list [\-C] | \-\-deleteall) [module_name]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage module позволяет устанавливать, удалять, отключать модули политики SELinux.

.SH "ПАРАМЕТРЫ"
.TP
.I  \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I   \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I   \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I   \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I   \-a, \-\-add
установить указанный модуль
.TP
.I   \-r, \-\-remove
удалить указанный модуль
.TP
.I   \-d \-\-disable
отключить указанный модуль
.TP
.I   \-e \-\-enable
включить указанный модуль
.TP
.I   \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I   \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I   \-C, \-\-locallist
вывести список локальных настроек

.SH ПРИМЕР
.nf
Вывести список всех модулей
# semanage module \-l
Отключить неограниченный модуль (unconfined)
# semanage module \-\-disable unconfined
Установить пользовательский модуль политики apache
# semanage module \-a myapache

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8),
.BR semodule (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
