.TH "semanage-permissive" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-permissive \- утилита разрешительного сопоставления для управления политикой SELinux
.SH "ОБЗОР"
.B semanage permissive [\-h] (\-a | \-d | \-l) [\-n] [\-N] [\-S STORE] [type]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Утилита semanage permissive позволяет добавить или удалить разрешительный модуль политики SELinux.

.SH "ПАРАМЕТРЫ"
.TP
.I  \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I   \-a, \-\-add
добавить запись указанного типа объекта
.TP
.I   \-d, \-\-delete
удалить запись указанного типа объекта
.TP
.I   \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I   \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I   \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I   \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP

.SH ПРИМЕР
.nf
Вывести список всех разрешительных модулей
# semanage permissive \-l
Сделать httpd_t (веб-сервер) разрешительным доменом
# semanage permissive \-a httpd_t

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
