.TH "semanage-node" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-node \- утилита для управления политикой SELinux, предназначенная для сопоставления узлов
.SH "ОБЗОР"
.B semanage node [\-h] [\-n] [\-N] [\-S STORE] [ \-\-add \-M NETMASK \-p PROTOCOL \-t TYPE \-r RANGE node | \-\-delete \-M NETMASK \-p PROTOCOL node | \-\-deleteall  | \-\-extract  | \-\-list [\-C] | \-\-modify \-M NETMASK \-p PROTOCOL \-t TYPE \-r RANGE node ]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage node управляет определениями типов узлов для IP-адресов.

.SH "ПАРАМЕТРЫ"
.TP
.I \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I   \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I   \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I   \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I   \-C, \-\-locallist
вывести список локальных настроек
.TP
.I   \-a, \-\-add
добавить запись указанного типа объекта
.TP
.I   \-d, \-\-delete
удалить запись указанного типа объекта
.TP
.I   \-m, \-\-modify
изменить запись указанного типа объекта
.TP
.I   \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I   \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I   \-D, \-\-deleteall
удалить все локальные настройки
.TP
.I   \-M NETMASK, \-\-netmask NETMASK
маска сети
.TP
.I   \-t TYPE, \-\-type TYPE
SELinux-тип для объекта
.TP
.I   \-r RANGE, \-\-range RANGE
диапазон безопасности MLS/MCS (только для систем с поддержкой MLS/MCS). По умолчанию SELinux-диапазон для сопоставления имени входа SELinux принимает значение диапазона записи пользователя SELinux. По умолчанию SELinux-диапазон для пользователя SELinux принимает значение s0.
.TP
.I   \-p PROTO, \-\-proto PROTO

Протокол для указанного порта (tcp|udp) или версия протокола Интернета для указанного узла (ipv4|ipv6).

.SH "АВТОРЫ"
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>
