.TH "semanage-interface" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-interface \- утилита для управления политикой SELinux, предназначенная для работы с сетевыми интерфейсами
.SH "ОБЗОР"
.B semanage interface [\-h] [\-n] [\-N] [\-S STORE] [ \-\-add \-t TYPE \-r RANGE interface | \-\-delete interface | \-\-deleteall  | \-\-extract  | \-\-list [\-C] | \-\-modify \-t TYPE \-r RANGE interface ]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage interface управляет метками, которые назначаются сетевым интерфейсам.

.SH "ПАРАМЕТРЫ"
.TP
.I \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I  \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I  \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I  \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I  \-C, \-\-locallist
вывести список локальных настроек
.TP
.I  \-a, \-\-add
добавить запись указанного типа объекта
.TP
.I  \-d, \-\-delete
удалить запись указанного типа объекта
.TP
.I  \-m, \-\-modify
изменить запись указанного типа объекта
.TP
.I  \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I  \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I  \-D, \-\-deleteall
удалить все локальные настройки
.TP
.I  \-t TYPE, \-\-type TYPE
SELinux-тип для объекта
.TP
.I \-r RANGE, \-\-range RANGE
диапазон безопасности MLS/MCS (только для систем с поддержкой MLS/MCS). По умолчанию SELinux-диапазон для сопоставления имени входа SELinux принимает значение диапазона записи пользователя SELinux. По умолчанию SELinux-диапазон для пользователя SELinux принимает значение s0.

.SH ПРИМЕР
.nf
Вывести список всех определений интерфейсов
# semanage interface \-l

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8)

.SH "AUTHOR"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
