.TH "semanage-import" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-import \- утилита импорта для управления политикой SELinux
.SH "ОБЗОР"
.B semanage import [\-h] [\-N] [\-S STORE] [\-f INPUT_FILE]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команды semanage import и semanage export можно использовать, чтобы извлечь изменения SELinux на одном компьютере и применить их к другому. В файл можно поместить целую группу команд semanage и применить их к компьютеру в одной транзакции.

.SH "ПАРАМЕТРЫ"
.TP
.I  \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I   \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I   \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I   \-f INPUT_FILE, \-\-input_file INPUT_FILE
входной файл
.SH ПРИМЕР
.nf
Импортировать изменения semanage с другого компьютера
# semanage import \-f semanage.mods

.SH "СМОТРИТЕ ТАКЖЕ"
.B selinux (8),
.B semanage (8),
.B semanage-export (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
