.TH "semanage-fcontext" "8" "20130617" "" ""
.SH "ИМЯ"
semanage\-fcontext \- утилита для управления политикой SELinux, предназначенная для работы с контекстами файлов

.SH "ОБЗОР"
.B semanage fcontext [\-h] [\-n] [\-N] [\-S STORE] [ \-\-add ( \-t TYPE \-f FTYPE \-r RANGE \-s SEUSER | \-e EQUAL ) FILE_SPEC ) | \-\-delete ( \-t TYPE \-f FTYPE | \-e EQUAL ) FILE_SPEC ) | \-\-deleteall  | \-\-extract  | \-\-list [\-C] | \-\-modify ( \-t TYPE \-f FTYPE \-r RANGE \-s SEUSER | \-e EQUAL ) FILE_SPEC ) ]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage fcontext используется для управления проставлением меток по умолчанию в файловой системе в системе SELinux. Эта команда с помощью регулярных выражений сопоставляет пути файлов с метками SELinux.

.SH "ПАРАМЕТРЫ"
.TP
.I  \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I   \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I   \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I   \-C, \-\-locallist
вывести список локальных настроек
.TP
.I   \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I   \-a, \-\-add
добавить запись указанного типа объекта
.TP
.I   \-d, \-\-delete
удалить запись указанного типа объекта
.TP
.I   \-m, \-\-modify
изменить запись указанного типа объекта
.TP
.I   \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I   \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I   \-D, \-\-deleteall
удалить все локальные настройки
.TP
.I   \-e EQUAL, \-\-equal EQUAL
Заменить путь к цели на путь к источнику при создании меток по умолчанию. Используется с fcontext. Необходимы аргументы путей к источнику и цели. Для целевого поддерева метки контекста будут проставляться тем же образом, который задан для источника.
.TP
.I   \-f [{a,f,d,c,b,s,l,p}], \-\-ftype [{a,f,d,c,b,s,l,p}]
Тип файла. Используется с fcontext. Требуется тип файла (показывается в поле режима по команде ls); например, используйте 'd' для соответствия только каталогам или 'f' для соответствия только обычным файлам. Могут передаваться следующие параметры типа файла: f (обычный файл), d (каталог), c (устройство символьного ввода-вывода), b (устройство блочного ввода-вывода), s (сокет), l (символическая ссылка), p (именованный канал). Если вы не укажете тип файла, по умолчанию будет установлен тип "all files" (все файлы).

.TP
.I   \-s SEUSER, \-\-seuser SEUSER
имя пользователя SELinux
.TP
.I   \-t TYPE, \-\-type TYPE
SELinux-тип для объекта
.TP
.I   \-r RANGE, \-\-range RANGE
диапазон безопасности MLS/MCS (только для систем с поддержкой MLS/MCS). По умолчанию SELinux-диапазон для сопоставления имени входа SELinux принимает значение диапазона записи пользователя SELinux. По умолчанию SELinux-диапазон для пользователя SELinux принимает значение s0.

.SH ПРИМЕР
.nf
.I выполните restorecon после установки контекста файлов
Добавьте контекст файлов для всего, что находится в /web
# semanage fcontext \-a \-t httpd_sys_content_t "/web(/.*)?"
# restorecon \-R \-v /web

Замените /home1 на /home при установке контекста файлов
# semanage fcontext \-a \-e /home /home1
# restorecon \-R \-v /home1

Выполните следующие команды для домашних каталогов, находящихся ниже каталога верхнего уровня, например /disk6/home
# semanage fcontext \-a \-t home_root_t "/disk6"
# semanage fcontext \-a \-e /home /disk6/home
# restorecon \-R \-v /disk6

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
