.TH "semanage-user" "8" "20130617" "" ""
.SH "ИМЯ"
.B semanage\-user \- утилита для управления политикой SELinux, предназначенная для сопоставления пользователей
.SH "ОБЗОР"
.B  semanage user [\-h] [\-n] [\-N] [\-S STORE] [ \-\-add ( \-L LEVEL \-R ROLES \-r RANGE SEUSER) | \-\-delete SEUSER | \-\-deleteall  | \-\-extract  | \-\-list [\-C] | \-\-modify ( \-L LEVEL \-R ROLES \-r RANGE SEUSER ) ]

.SH "ОПИСАНИЕ"
semanage используется для настройки определённых элементов политики SELinux без необходимости изменения или перекомпиляции исходного текста политики. Команда semanage user управляет сопоставлением пользователей SELinux с ролями и уровнями MLS/MCS.

.SH "ПАРАМЕТРЫ"
.TP
.I   \-h, \-\-help
показать это справочное сообщение и выйти
.TP
.I   \-n, \-\-noheading
не показывать заголовок при выводе указанного типа объекта
.TP
.I   \-N, \-\-noreload
не перезагружать политику после фиксации
.TP
.I   \-S STORE, \-\-store STORE
выбрать для управления альтернативное хранилище политики SELinux
.TP
.I   \-C, \-\-locallist
вывести список локальных настроек
.TP
.I   \-a, \-\-add
добавить запись указанного типа объекта
.TP
.I   \-d, \-\-delete
удалить запись указанного типа объекта
.TP
.I   \-m, \-\-modify
изменить запись указанного типа объекта
.TP
.I   \-l, \-\-list
вывести список записей указанного типа объекта
.TP
.I   \-E, \-\-extract
извлечь настраиваемые команды для использования в транзакции
.TP
.I   \-D, \-\-deleteall
удалить все локальные настройки
.TP
.I   \-L LEVEL, \-\-level LEVEL
уровень SELinux по умолчанию для пользователя SELinux, s0 (только для систем с поддержкой MLS/MCS)
.TP
.I   \-r RANGE, \-\-range RANGE
диапазон безопасности MLS/MCS (только для систем с поддержкой MLS/MCS). По умолчанию SELinux-диапазон для сопоставления имени входа SELinux принимает значение диапазона записи пользователя SELinux. По умолчанию SELinux-диапазон для пользователя SELinux принимает значение s0.
.TP
.I   \-R [ROLES], \-\-roles [ROLES]
роли SELinux. Если ролей несколько, их необходимо перечислить через пробелы и заключить этот перечень в кавычки. Или можно несколько раз указать \-R.

.SH ПРИМЕР
.nf
Вывести список пользователей SELinux
# semanage user \-l
Изменить группы для пользователя staff_u
# semanage user \-m \-R "system_r unconfined_r staff_r" staff_u
Добавить уровень для пользователей TopSecret
# semanage user \-a \-R "staff_r" \-rs0\-TopSecret topsecret_u

.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR semanage (8),
.BR semanage\-login (8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
