.TH LOAD_POLICY "8" "Май 2003" "Security Enhanced Linux" NSA
.SH ИМЯ
load_policy \- загрузить новую политику SELinux в ядро

.SH ОБЗОР
.B load_policy 
[\-qi]
.br
.SH ОПИСАНИЕ
.PP
load_policy загружает установленный файл политики в ядро.
Существующие значения логических переключателей политики автоматически сохраняются при перезагрузках политики, а не сбрасываются на установленные в файле политики значения по умолчанию.

.SH "ПАРАМЕТРЫ"
.TP
.B \-q
Отменить предупредительные сообщения.
.TP
.B \-i
Начальная загрузка политики. Следует использовать, только если политика загружается впервые с момента запуска (обычно вызывается из initramfs).

.SH "СОСТОЯНИЕ ВЫХОДА"
.TP
.B 0
Успешно
.TP
.B 1
Недействительный параметр
.TP
.B 2
Не удалось загрузить политику
.TP
.B 3
Не удалось выполнить начальную загрузку политики, запрошен принудительный режим
.SH СМОТРИТЕ ТАКЖЕ
.BR booleans (8)
.SH АВТОРЫ
.nf
Эта страница руководства была написана Dan Walsh <dwalsh@redhat.com>.
Программа была написана Stephen Smalley <sds@tycho.nsa.gov>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
