.TH SECON "1" "Апрель 2006" "Security Enhanced Linux" NSA
.SH ИМЯ
secon \- показать контекст SELinux для файла, программы или ввода пользователя.
.SH ОБЗОР
.B secon
[\fB-hVurtscmPRfLp\fR]
[\fICONTEXT\fR]
.br
[\fB--file\fR]
\fIFILE\fR
.br
[\fB--link\fR]
\fIFILE\fR
.br
[\fB--pid\fR]
\fIPID\fR
.SH ОПИСАНИЕ
.PP
Просмотр части контекста. Контекст берётся из файла, идентификатора процесса, ввода пользователя или контекста, в котором была изначально запущена команда
.B secon.
.TP
\fB\-V\fR, \fB\-\-version\fR
показать текущую версию secon
.TP
\fB\-h\fR, \fB\-\-help\fR
показать сведения об использовании secon
.TP
\fB\-P\fR, \fB\-\-prompt\fR
вывести данные в формате, подходящем для запроса
.TP
\fB\-C\fR, \fB\-\-color\fR
вывести данные с назначенными цветовыми кодами ANSI (требуется \-P)
.TP
\fB\-u\fR, \fB\-\-user\fR
показать пользователя контекста безопасности
.TP
\fB\-r\fR, \fB\-\-role\fR
показать роль контекста безопасности
.TP
\fB\-t\fR, \fB\-\-type\fR
показать тип контекста безопасности
.TP
\fB\-s\fR, \fB\-\-sensitivity\fR
показать уровень конфиденциальности контекста безопасности
.TP
\fB\-c\fR, \fB\-\-clearance\fR
показать уровень допуска контекста безопасности
.TP
\fB\-m\fR, \fB\-\-mls-range\fR
показать для контекста безопасности в виде диапазона уровень конфиденциальности и уровень допуска
.TP
\fB\-R\fR, \fB\-\-raw\fR
вывести уровень конфиденциальности и уровень допуска в непреобразованном формате
.TP
\fB\-f\fR, \fB\-\-file\fR
получить контекст из указанного файла FILE
.TP
\fB\-L\fR, \fB\-\-link\fR
получить контекст из указанного файла FILE (не выполнять переход по символическим ссылкам)
.TP
\fB\-p\fR, \fB\-\-pid\fR
получить контекст из указанного идентификатора процесса PID
.TP
\fB\-\-pid\-exec\fR
получить контекст exec из указанного идентификатора процесса PID
.TP
\fB\-\-pid\-fs\fR
получить контекст fscreate из указанного идентификатора процесса PID
.TP
\fB\-\-pid\-key\fR
получить контекст key из указанного идентификатора процесса PID
.TP
\fB\-\-current\fR, \fB\-\-self\fR
получить контекст из текущего процесса
.TP
\fB\-\-current\-exec\fR, \fB\-\-self\-exec\fR
получить контекст exec из текущего процесса
.TP
\fB\-\-current\-fs\fR, \fB\-\-self\-fs\fR
получить контекст fscreate из текущего процесса
.TP
\fB\-\-current\-key\fR, \fB\-\-self\-key\fR
получить контекст key из текущего процесса
.TP
\fB\-\-parent\fR
получить контекст из родителя текущего процесса
.TP
\fB\-\-parent\-exec\fR
получить контекст exec из родителя текущего процесса
.TP
\fB\-\-parent\-fs\fR
получить контекст fscreate из родителя текущего процесса
.TP
\fB\-\-parent\-key\fR
получить контекст key из родителя текущего процесса
.PP
Можно предоставить дополнительный аргумент
.I CONTEXT
- он будет использоваться, если не заданы параметры, согласно которым
.B secon
получает контекст из другого источника.
Если этим аргументом является  
.I -
(знак дефиса), контекст будет прочтён из stdin.
.br
Если аргумент отсутствует,
.B secon
попытается прочитать контекст из stdin, если это не tty; в ином случае 
.B secon
будет действовать так, как если бы был передан параметр \fB\-\-self\fR.
.PP
Если не передан ни один из параметров \fB\-\-user\fR, \fB\-\-role\fR, \fB\-\-type\fR, \fB\-\-level\fR или
\fB\-\-mls\-range\fR, будут выведены все они.
.PP
.SH СМОТРИТЕ ТАКЖЕ
.BR chcon (1)
.SH АВТОРЫ
.nf
James Antill (james.antill@redhat.com).
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
