.TH CHCAT "8" "September 2005" "chcat" "User Commands"
.SH NAME
chcat \- change file SELinux security category
.SH SYNOPSIS
.B chcat
\fIcategory file\fR...
.br
.B chcat -l 
\fIcategory user\fR...
.br
.B chcat
\fI[[+|-]category...]  file\fR...
.br
.B chcat -l 
\fI[[+|-]category...]  user\fR...
.br
.B chcat
[\fI-d\fR] \fIfile\fR...
.br
.B chcat -l 
[\fI-d\fR] \fIuser\fR...
.br
.B chcat
\fI-L\fR [ \-l ] [ user ... ]
.br
.SH DESCRIPTION
.PP
Change/Remove the security \fIcategory\fR for each \fIfile\fR or \fIuser\fR.
.PP
Use +/- to add/remove categories from a \fIfile\fR or \fIuser\fR.
.PP
.B
Note:
When removing a category you must specify '\-\-' on the command line before using the \-Category syntax.  This tells the command that you have finished entering options and are now specifying a category name instead.

.TP
\fB\-d\fR
delete the category from each FILE/USER.
.TP
\fB\-L\fR
list available categories.
.TP
\fB\-l\fR
Tells chcat to operate on users instead of files.
.SH "SEE ALSO"
.TP
chcon(1), selinux(8), semanage(8)
.PP
.br
When operating on files this script wraps the chcon command.
.SH "FILES"
/etc/selinux/{SELINUXTYPE}/setrans.conf 
.br
/etc/selinux/{SELINUXTYPE}/seusers

