.TH "sepolicy-interface" "8" "20121222" "" ""
.SH "NAME"
sepolicy-interface \- Print interface information based on the installed SELinux Policy

.SH "SYNOPSIS"

.br
.B sepolicy interface  [\-h] [\-c] [\-v] [\-f FILE] [\-a | \-u | \-l | \-i INTERFACE [INTERFACE ... ]]

.SH "DESCRIPTION"
Use sepolicy interface to print information of interface macros
between domains in SELinux policy modules, as used in Reference
Policy. The information is based on installed on-disk representation
of the SELinux Policy and it may be different from the policy which is
currently loaded.

.SH "OPTIONS"
.TP
.I                \-a, \-\-list_admin
List all domains with admin interface
.TP
.I                \-c, \-\-compile
Test compile of interfaces
.TP
.I                \-h, \-\-help
Display help message
.TP
.I                \-i, \-\-interface
Interface(s) to be displayed
.TP
.I                \-l, \-\-list
List all interfaces
.TP
.I                \-u, \-\-list_user
List all domains with SELinux user role interface
.TP
.I                \-v, \-\-verbose
Display extended information about the interface including parameters and description if available.
.TP
.I                \-f, \-\-file
Interface file to be explored

.SH EXAMPLE
.nf
Show description of given interface
# sepolicy interface -vi samba_rw_config
List interfaces in given interface file and show their description
# sepolicy interface -f my_policy.if -lv
Run compile test for all interfaces in given file
# sepolicy interface -f my_policy.if -lc

.SH "AUTHOR"
This man page was written by Daniel Walsh <dwalsh@redhat.com>

.SH "SEE ALSO"
sepolicy(8), selinux(8)
