.TH "sepolicy-booleans" "8" "20121112" "" ""
.SH "NAME"
sepolicy-booleans \- Query SELinux Policy to see description of booleans

.SH "SYNOPSIS"

.br
.B sepolicy booleans [\-h] [ \-a | \-b booleanname ... ]

.SH "DESCRIPTION"
sepolicy booleans will show all booleans and their descriptions, or you can 
choose individual booleans to display

.SH "OPTIONS"
.TP
.I                \-h, \-\-help       
Display help message
.TP
.I                \-a, \-\-all
Display all boolean descriptions
.TP
.I                \-b, \-\-boolean
boolean to get description

.SH "AUTHOR"
This man page was written by Daniel Walsh <dwalsh@redhat.com>

.SH "SEE ALSO"
sepolicy(8), selinux(8), getsebool(8), setsebool(8)
