.TH "selinux-polgengui" "8" "8 апреля 2013" "Руководство по утилитам настройки системы"

.SH ИМЯ
selinux\-polgengui \- утилита для создания политики SELinux

.SH ОБЗОР
.B selinux-polgengui

.SH ОПИСАНИЕ
\fBselinux-polgengui\fP - графическая утилита, которую можно использовать, чтобы создать платформу для сборки политики SELinux.
.SH ПАРАМЕТРЫ
Нет

.SH ФАЙЛЫ
\fi/usr/bin/selinux-polgengui\fP

.SH Примеры
Чтобы запустить программу, введите:

selinux-polgengui

.PP
.SH "СМОТРИТЕ ТАКЖЕ"
.TP
selinux(1), sepolicy(8), sepolicy-generate(8)
.PP

.SH СООБЩЕНИЯ ОБ ОШИБКАХ
Отправляйте сообщения об ошибках по адресу <http://bugzilla.redhat.com>.

.SH ЛИЦЕНЗИЯ И АВТОРЫ
\fBselinux-polgengui\fP распространяется на условиях Стандартной Общественной Лицензии 
GNU, авторские права принадлежат Red Hat, Inc.
.br
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>. Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
