.TH "system-config-selinux" "8" "8 апреля 2013" "Руководство по утилитам настройки системы"

.SH ИМЯ
system\-config\-selinux \- утилита для управления SELinux

.SH ОБЗОР
.B system-config-selinux

.SH ОПИСАНИЕ
Утилита \fBsystem-config-selinux\fP предоставляет графический интерфейс для управления конфигурацией SELinux.

.SH ПАРАМЕТРЫ
Нет

.SH ФАЙЛЫ
\fi/usr/bin/system-config-selinux\fP

.SH Примеры
Чтобы запустить программу, введите:

system-config-selinux

.PP
.SH "СМОТРИТЕ ТАКЖЕ"
.TP
selinux(1), semanage(8)
.PP

.SH СООБЩЕНИЯ ОБ ОШИБКАХ
Отправляйте сообщения об ошибках по адресу <http://bugzilla.redhat.com>.

.SH ЛИЦЕНЗИЯ И АВТОРЫ
\fBsystem-config-selinux\fP распространяется на условиях Стандартной Общественной Лицензии 
GNU, авторские права принадлежат Red Hat, Inc.
.br
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>. Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
