.TH CHECKPOLICY 8
.SH ИМЯ
checkpolicy \- компилятор политики SELinux
.SH ОБЗОР
.B checkpolicy
.I "[\-b[F]] [\-C] [\-d] [\-U handle_unknown (allow,deny,reject)] [\-M] [\-c policyvers] [\-o output_file] [\-S] [\-t target_platform (selinux,xen)] [\-V] [input_file]"
.br
.SH "ОПИСАНИЕ"
Эта страница руководства содержит описание команды 
.BR checkpolicy.
.PP
.B checkpolicy
- это программа, которая проверяет и компилирует конфигурацию политики безопасности SELinux в двоичное представление, которое можно загрузить в ядро. Если имя входного файла не указано, checkpolicy попытается выполнить чтение из policy.conf или policy (если указан флаг \-b).

.SH ПАРАМЕТРЫ
.TP
.B \-b,\-\-binary
Прочитать существующий двоичный файл политики, а не исходный файл policy.conf.
.TP
.B \-F,\-\-conf
Записать файл policy.conf, а не двоичный файл политики. Этот параметр можно использовать только при работе с двоичным файлом политики.
.TP
.B \-C,\-\-cil
Записать файл политики CIL, а не двоичный файл политики.
.TP
.B \-d,\-\-debug
Войти в режим отладки после загрузки политики.
.TP
.B \-U,\-\-handle-unknown <action>
Указать, как ядро должно обрабатывать неизвестные классы или разрешения (запрещать, разрешать или отклонять).
.TP
.B \-M,\-\-mls
Включить политику MLS при проверке и компиляции политики.
.TP
.B \-c policyvers
Указать версию политики (по умолчанию используется последняя).
.TP
.B \-o,\-\-output filename
Записать двоичный файл политики с указанным именем файла.
.TP
.B \-S,\-\-sort
Сортировать прочие контексты (ocontexts) перед записью двоичной политики. Этот параметр позволяет задать соответствие вывода checkpolicy двоичным политикам, созданным с помощью semanage и secilc.
.TP
.B \-t,\-\-target
Указать целевую платформу (selinux или xen).
.TP
.B \-V,\-\-version
Показать сведения о версии.
.TP
.B \-h,\-\-help
Показать сведения об использовании.

.SH "СМОТРИТЕ ТАКЖЕ"
Документация SELinux Reference Policy по адресу https://github.com/SELinuxProject/refpolicy/wiki

.SH АВТОРЫ
Эта страница руководства была написана Árpád Magosányi <mag@bunuel.tii.matav.hu>,
и отредактирована Stephen Smalley <sds@tycho.nsa.gov>.
Программа была написана Stephen Smalley <sds@tycho.nsa.gov>.
Перевод на русский язык выполнила Олеся Герасименко <gammaray@basealt.ru>.
