.TH CHECKMODULE 8
.SH ИМЯ
checkmodule \- компилятор модулей политики SELinux
.SH ОБЗОР
.B checkmodule
.I "[\-h] [\-b] [\-C] [\-m] [\-M] [\-U handle_unknown ] [\-V] [\-o output_file] [input_file]"
.SH "ОПИСАНИЕ"
Эта страница руководства содержит описание команды
.BR checkmodule.
.PP
.B checkmodule
- это программа, которая проверяет и компилирует модуль политики безопасности SELinux в двоичное представление.  Она может создавать либо базовый модуль политики (по умолчанию), либо небазовый модуль политики (параметр \-m); обычно требуется создать небазовый модуль политики для последующего добавления в существующее хранилище модулей, в котором уже есть базовый модуль, предоставленный базовой политикой. Используйте semodule_package, чтобы объединить этот модуль с соответствующим необязательным файлом контекстов файлов и таким образом создать пакет политики, а затем используйте semodule для установки пакета модуля в хранилище модулей и загрузите получившуюся политику.

.SH ПАРАМЕТРЫ
.TP
.B \-b,\-\-binary
Прочитать существующий файл двоичного модуля политики вместо исходного файла модуля политики. Этот параметр полезен при разработке/отладке.
.TP
.B \-C,\-\-cil
Записать файл политики CIL, а не двоичный файл политики.
.TP
.B \-h,\-\-help
Вывести справку.
.TP
.B \-m
Создать небазовый модуль политики.
.TP
.B \-M,\-\-mls
Включить поддержку MLS/MCS при проверке и компиляции модуля политики.
.TP
.B \-V,\-\-version
Показать версии политики, созданные этой программой. Обратите внимание, что в настоящее время не поддерживается сборка более ранних версий.
.TP
.B \-o,\-\-output filename
Записать файл двоичного модуля политики с указанным именем файла.
Без указания имени файла checkmodule только проверит синтаксис исходного файла модуля и не будет создавать двоичный модуль.
.TP
.B \-U,\-\-handle-unknown <action>
Указать, как ядро должно обрабатывать неизвестные классы или разрешения (запрещать, разрешать или отклонять).

.SH ПРИМЕР
.nf
# Собрать небазовый модуль политики с включённой системой безопасности MLS/MCS.
$ checkmodule \-M \-m httpd.te \-o httpd.mod
.fi

.SH "СМОТРИТЕ ТАКЖЕ"
.B semodule(8), semodule_package(8)
Документация SELinux Reference Policy по адресу https://github.com/SELinuxProject/refpolicy/wiki


.SH АВТОРЫ
Эта страница руководства была скопирована со страницы руководства checkpolicy, написанной Árpád Magosányi <mag@bunuel.tii.matav.hu>,
и отредактирована Dan Walsh <dwalsh@redhat.com>.
Программа была написана Stephen Smalley <sds@tycho.nsa.gov>.
Перевод на русский язык выполнила Олеся Герасименко <gammaray@basealt.ru>.
