.TH "sepolicy-transition" "8" "20121005" "" ""
.SH "ИМЯ"
sepolicy-transition \- проанализировать политику SELinux и создать отчёт о переходах процессов

.SH "ОБЗОР"

.br
.B sepolicy transition [\-h] \-s SOURCE

.br
.B sepolicy transition [\-h] \-s SOURCE \-t TARGET

.SH "ОПИСАНИЕ"
Утилита sepolicy transition покажет все домены, в которые может перейти указанный исходный домен SELinux, включая точку входа.

Если указан целевой домен, команда sepolicy transition проанализирует политику на предмет наличия путей перехода из исходного домена в целевой домен и выведет список этих путей. Если переход возможен, эта утилита выведет все пути перехода из исходного домена в целевой домен.

.SH "ПАРАМЕТРЫ"
.TP
.I                \-h, \-\-help       
Показать справочное сообщение
.TP
.I                \-s, \-\-source
Указать тип исходного домена SELinux
.TP
.I                \-t, \-\-target
Указать тип целевого домена SELinux

.SH "СМОТРИТЕ ТАКЖЕ"
sepolicy(8), selinux(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
