.TH "sepolicy" "8" "20121005" "" ""
.SH "ИМЯ"
sepolicy \- утилита анализа политики SELinux

.SH "ОБЗОР"
.B sepolicy [-h] [-P policy_path ] {booleans,communicate,generate,interface,manpage,network,transition} OPTIONS

.br
Аргументы:
.br

.B    booleans
.br
Отправить запрос к политике SELinux, чтобы просмотреть описание логических переключателей
.B sepolicy-boolean(8)
.br

.B    communicate
.br
Отправить запрос к политике SELinux, чтобы узнать, могут ли домены связываться друг с другом
.B sepolicy-communicate(8)
.br

.B    generate
.br
Создать шаблон модуля политики SELinux
.B sepolicy-generate(8)
.br

.B    gui
.br
Запустить графический интерфейс пользователя политики SELinux (требуется пакет policycoreutils-gui)
.B sepolicy-gui(8)
.br

.B    interface
.br 
.br
Вывести сведения интерфейса политики SELinux
.B sepolicy-interface(8)
.br

.B    manpage
.br
Создать man-страницы SELinux 
.B sepolicy-manpage(8)
.br

.B    network
.br
Запросить сведения о сети политики SELinux
.B sepolicy-network(8)
.br

.B    transition 
.br
Отправить запрос к политике SELinux, чтобы узнать, как исходный домен процесса может перейти в целевой домен процесса 
.B sepolicy-transition(8)

.SH "ОПИСАНИЕ"
sepolicy - это набор средств, опрашивающих установленную политику SELinux и создающих полезные отчёты,  man-страницы или даже новые модули политики.
Параметры и их описание доступны на man-страницах соответствующих аргументов.

.SH "ПАРАМЕТРЫ"
.TP
.I                \-P, \-\-policy
Альтернативная политика для анализа. (По умолчанию: текущая установленная политика /sys/fs/selinux/policy)
.TP
.I                \-h, \-\-help       
Показать справочное сообщение

.SH "СМОТРИТЕ ТАКЖЕ"
selinux(8), sepolicy-booleans(8), sepolicy-communicate(8), sepolicy-generate(8),sepolicy-gui(8), sepolicy-interface(8),  sepolicy-network(8), sepolicy-manpage(8), sepolicy-transition(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
