.TH "sepolicy-interface" "8" "20121222" "" ""
.SH "ИМЯ"
sepolicy-interface \- вывести сведения об интерфейсах на основе установленной политики SELinux

.SH "ОБЗОР"

.br
.B sepolicy interface  [\-h] [\-c] [\-v] [\-a | \-u | \-l | \-i INTERFACE [INTERFACE ... ]]

.SH "ОПИСАНИЕ"
Используйте утилиту sepolicy interface для вывода сведений об интерфейсах на основе политики SELinux.

.SH "ПАРАМЕТРЫ"
.TP
.I                \-a, \-\-list_admin
Вывести список всех доменов с интерфейсом администратора
.TP
.I                \-c, \-\-compile
Проверить сборку интерфейсов
.TP
.I                \-h, \-\-help       
Показать справочное сообщение
.TP
.I                \-i, \-\-interface
Интерфейс (интерфейсы), которые следует показать
.TP
.I                \-l, \-\-list
Вывести список всех интерфейсов
.TP
.I                \-u, \-\-list_user
Вывести список всех доменов с интерфейсом роли пользователя SELinux
.TP
.I                \-v, \-\-verbose
Показать расширенные сведения об интерфейсе, включая параметры и описание (если доступно).

.SH "СМОТРИТЕ ТАКЖЕ"
sepolicy(8), selinux(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
