.TH "sepolicy-manpage" "8" "20121005" "" ""
.SH "ИМЯ"
sepolicy-manpage \- создать man-страницу на основе установленной политики SELinux

.SH "ОБЗОР"

.br
.B sepolicy manpage [\-w] [\-h] [\-p PATH ] [\-r ROOTDIR ] [\-a | \-d ]

.SH "ОПИСАНИЕ"
Используйте утилиту sepolicy manpage для создания man-страниц на основе политики SELinux.

.SH "ПАРАМЕТРЫ"
.TP
.I                \-a, \-\-all        
Создать man-страницы для всех доменов
.TP
.I                \-d, \-\-domain     
Создать man-страницу для указанного домена. (Поддерживает несколько команд)
.TP
.I                \-h, \-\-help       
Показать справочное сообщение
.TP
.I                \-p, \-\-path
Указать каталог для сохранения созданных man-страниц. (По умолчанию: /tmp)
.TP
.I                \-r, \-\-root
Указать альтернативный корневой каталог для создания man-страниц. (По умолчанию: /)
.TP
.I                \-w, \-\-web
Создать дополнительные man-страницы в формате HTML для указанного домена (доменов).

.SH "СМОТРИТЕ ТАКЖЕ"
sepolicy(8), selinux(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
