.TH "sepolicy-booleans" "8" "20121112" "" ""
.SH "ИМЯ"
sepolicy-booleans \- запросить описание логических переключателей из политики SELinux

.SH "ОБЗОР"

.br
.B sepolicy booleans [\-h] [ \-a | \-b booleanname ... ]

.SH "ОПИСАНИЕ"
Утилита sepolicy booleans показывает все логические переключатели и их описание (либо можно вывести описание для отдельных логических переключателей)

.SH "ПАРАМЕТРЫ"
.TP
.I                \-h, \-\-help       
показать справочное сообщение
.TP
.I                \-a, \-\-all
показать все описания логических переключателей
.TP
.I                \-b, \-\-boolean
логический переключатель, для которого следует получить описание

.SH "СМОТРИТЕ ТАКЖЕ"
sepolicy(8), selinux(8), getsebool(8), setsebool(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
