.TH "sepolicy-gui" "8" "20121005" "" ""
.SH "ИМЯ"
sepolicy-gui \- графический интерфейс пользователя политики SELinux

.SH "ОБЗОР"

Общие параметры

.B sepolicy gui [\-h ] [ \-d DOMAIN ]

.br

.SH "ОПИСАНИЕ"
Используйте утилиту \fBsepolicy gui\fP для запуска графического интерфейса пользователя, с помощью которого можно посмотреть, как SELinux ограничивает различные домены процессов.

.SH "ПАРАМЕТРЫ"
.TP
.I                \-h, \-\-help
Показать справочное сообщение
.TP
.I                \-d, \-\-domain
Инициализировать для выбранного домена графический интерфейс пользователя 

.SH "СМОТРИТЕ ТАКЖЕ"
sepolicy(8), selinux(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
