.TH "sepolicy-communicate" "8" "20121005" "" ""
.SH "ИМЯ"
sepolicy-communicate \- создать отчёт, который покажет, могут ли связываться два домена политики SELinux

.SH "ОБЗОР"

.br
.B sepolicy communicate [\-h] \-s SOURCE \-t TARGET [\-c TCLASS] [\-S SOURCEACCESS] [\-T TARGETACCESS]

.SH "ОПИСАНИЕ"
Команда sepolicy communicate позволяет проанализировать политику SELinux, чтобы узнать, может ли исходный домен SELinux связываться с целевым доменом SELinux.
Команда по умолчанию проверяет, имеются ли какие-либо типы файлов, которые может записывать исходный домен и читать целевой домен.

.SH "ПАРАМЕТРЫ"
.TP
.I                \-c, \-\-class
Указать класс SELinux, который исходный домен попытается использовать для связи с целевым доменом. По умолчанию: file.
.TP
.I                \-h, \-\-help       
Показать справочное сообщение
.TP
.I                \-s, \-\-source
Указать тип исходного домена SELinux
.TP
.I                \-S, \-\-sourceaccess
Указать список доступов, используемых типом исходного домена SELinux для связи с целевым доменом. По умолчанию: Open, Write.
.TP
.I                \-t, \-\-target
Указать тип целевого домена SELinux
.TP
.I                \-T, \-\-targetaccess
Указать список доступов, используемых типом целевого домена SELinux для получения обращений от исходного домена. По умолчанию: Open, Read.

.SH "СМОТРИТЕ ТАКЖЕ"
sepolicy(8), selinux(8)

.SH "АВТОРЫ"
Эта man-страница была написана Daniel Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.

