.TH "avcstat" "8" "18 ноября 2004" "dwalsh@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
avcstat \- показать статистику AVC (Access Vector Cache, кэш вектора доступа) SELinux
.
.SH "ОБЗОР"
.B avcstat
.RB [ \-c ]
.RB [ \-f
.IR status_file ]
.RI [ interval ]
.
.SH "ОПИСАНИЕ"
Показать статистику AVC SELinux.  Если указан параметр
.I interval
, программа будет выполняться циклами, показывая обновлённую статистику каждые
.I interval
секунд.
По умолчанию показываются относительные значения. 
.
.SH ПАРАМЕТРЫ
.TP
.B \-c
Показать совокупные значения.
.TP
.B \-f
Указывает расположение файла статистики AVC, по умолчанию это
.IR /sys/fs/selinux/avc/cache_stats .
.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8)
.
.SH АВТОРЫ
Эта страница руководства была написана Dan Walsh <dwalsh@redhat.com>.
Программа была написана James Morris <jmorris@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
