.TH "getenforce" "8" "7 апреля 2004" "dwalsh@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
getenforce \- получить текущий режим SELinux
.
.SH "ОБЗОР"
.B getenforce
.
.SH "ОПИСАНИЕ"
.B getenforce
сообщает, в каком режиме работает SELinux (принудительный, разрешительный, отключённый).
.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR setenforce (8),
.BR selinuxenabled (8)
.
.SH АВТОРЫ
Dan Walsh, <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
