.TH "getsebool" "8" "11 августа 2004" "dwalsh@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
getsebool \- получить логические значения SELinux
.
.SH "ОБЗОР"
.B getsebool
.RB [ \-a ]
.RI [ boolean ]
.
.SH "ОПИСАНИЕ"
.B getsebool 
сообщает, где включён или отключён конкретный логический переключатель
или все логические переключатели SELinux.
В некоторых ситуациях для логического переключателя может существовать
ожидающее изменение (переход из одного состояние в другое) - getsebool
сообщит об этом.
Ожидающее значение - то значение, которое будет применено при
следующей фиксации логического переключателя.

Установка значений логических переключателей выполняется в два этапа;
сначала изменяется ожидающее значение, а затем логические переключатели
фиксируются, в результате чего их активные значения заменяются 
ожидающими значениями. Это позволяет изменить группу логических
переключателей за одну транзацию, задав все необходимые ожидающие
значения и затем одновременно зафиксировав их.
.
.SH ПАРАМЕТРЫ
.TP
.B \-a
Показать все логические переключатели SELinux.
.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR setsebool (8),
.BR booleans (8)
.
.SH АВТОРЫ
Эта страница руководства была написана Dan Walsh <dwalsh@redhat.com>.
Программа была написана Tresys Technology.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
