.TH "matchpathcon" "8" "21 апреля 2005" "dwalsh@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
matchpathcon \- получить текущий контекст безопасности SELinux для указанного пути из конфигурации контекстов файлов
.
.SH "ОБЗОР"
.B matchpathcon
.RB [ \-V ]
.RB [ \-N ]
.RB [ \-n ]
.RB [ \-m
.IR type ]
.RB [ \-f
.IR file_contexts_file ]
.RB [ \-p
.IR prefix ]
.RB [ \-P
.IR policy_root_path ]
.I filepath...
.
.SH "ОПИСАНИЕ"
.BR matchpathcon
опрашивает системную политику и выводит контекст безопасности по умолчанию, связанный с путём к файлу.

.B Примечание:
Одинаковые пути могут иметь разные контексты безопасности в зависимости от типа файла (обычный файл, каталог, файл связи, файл знаков ...).

.B matchpathcon 
также будет учитывать тип файла при определении контекста безопасности по умолчанию (если файл существует). Если файл не существует, сопоставление по типу файла не будет выполнено.
.
.SH ПАРАМЕТРЫ
.TP
.BI \-m " type"
Принудительно указать тип файла для поиска.
Действительные типы:
.BR file ", " dir ", "pipe ", " chr_file ", " blk_file ", "
.BR lnk_file ", " sock_file .
.TP
.B \-n
Не показывать путь.
.TP
.B \-N
Не использовать преобразования.
.TP
.BI \-f " file_context_file"
Использовать альтернативный файл file_context
.TP
.BI \-p " prefix"
Использовать префикс для ускорения преобразований
.TP
.BI \-P " policy_root_path"
Использовать альтернативный корневой путь к политике
.TP
.B \-V
Проверить контекст файла на диске на соответствие параметрам по умолчанию
.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux "(8), "
.BR matchpathcon (3)
.
.SH АВТОРЫ
Эта страница руководства была написана Dan Walsh <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
