.TH "selinuxenabled" "8" "7 апреля 2004" "dwalsh@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
selinuxenabled \- утилита для использования внутри сценариев оболочки, которая позволяет определить, включён ли selinux
.
.SH "ОБЗОР"
.B selinuxenabled
.
.SH "ОПИСАНИЕ"
Показывает, включён или отключён SELinux.
.
.SH "СОСТОЯНИЕ ВЫХОДА"
Выход с состоянием 0, если SELinux включён, и 1, если он отключён.
.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR setenforce (8),
.BR getenforce (8)
.
.SH АВТОРЫ
Dan Walsh, <dwalsh@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
