.TH "togglesebool" "8" "26 октября 2004" "sgrubb@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
togglesebool \- переключить текущее значение логического переключателя SELinux
.
.SH "ОБЗОР"
.B togglesebool
.I boolean...
.
.SH "ОПИСАНИЕ"
.B togglesebool
переключает текущее значение списка логических переключателей. Если текущее значение 1,
то оно будет заменено на 0, и наоборот. Меняются только "находящиеся в памяти" значения;
параметры загрузки остаются без изменений. 
.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR selinux (8),
.BR booleans (8),
.BR getsebool (8),
.BR setsebool (8)
.
.SH АВТОРЫ
Эта страница руководства была написана Steve Grubb <sgrubb@redhat.com>.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
