.TH "restorecon" "8" "2002031409" "" ""
.SH "NAME"
restorecon \- restore file(s) default SELinux security contexts.

.SH "SYNOPSIS"
.B restorecon
.I [\-o outfilename ] [\-R] [\-n] [\-p] [\-v] [\-e directory ] pathname...
.P
.B restorecon
.I \-f infilename [\-o outfilename ] [\-e directory ] [\-R] [\-n] [\-p] [\-v] [\-F]

.SH "DESCRIPTION"
This manual page describes the
.BR restorecon
program.
.P
This program is primarily used to set the security context
(extended attributes) on one or more files. 
.P
It can be run at any time to correct errors, to add support for
new policy, or with the \-n option it can just check whether the file
contexts are all as you expect.

.SH "OPTIONS"
.TP 
.B \-i
ignore files that do not exist
.TP 
.B \-f infilename
infilename contains a list of files to be processed by application. Use \- for stdin.
.TP 
.B \-e directory
directory to exclude (repeat option for more than one directory.)
.TP 
.B \-R \-r
change files and directories file labels recursively
.TP 
.B \-n
don't change any file labels.
.TP 
.B \-o outfilename
save list of files with incorrect context in outfilename.
.TP
.B \-p
show progress by printing * every 1000 files.
.TP 
.B \-v
show changes in file labels.
.TP 
.B \-vv
show changes in file labels, if type, role, or user are changing.
.TP 
.B \-F
Force reset of context to match file_context for customizable files, or the user section, if it has changed. 
.TP 
.SH "ARGUMENTS"
.B pathname...
The pathname for the file(s) to be relabeled. 
.SH NOTE
restorecon does not follow symbolic links.

.SH "AUTHOR"
This man page was written by Dan Walsh <dwalsh@redhat.com>.
Some of the content of this man page was taken from the setfiles 
man page written by Russell Coker <russell@coker.com.au>.
The program was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
.BR load_policy (8),
.BR checkpolicy (8)
.BR setfiles (8)
