.TH "getenforce" "1" "7 April 2004" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
getenforce \- get the current mode of SELinux
.SH "SYNOPSIS"
.B getenforce

.SH "DESCRIPTION"
.B getenforce
reports whether SELinux is enforcing, permissive, or disabled.

.SH AUTHOR	
Dan Walsh, <dwalsh@redhat.com>

.SH "SEE ALSO"
selinux(8), setenforce(8), selinuxenabled(8)
