.TH "getsebool" "8" "11 Aug 2004" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
getsebool \- get SELinux boolean value(s)
.
.SH "SYNOPSIS"
.B getsebool
.RB [ \-a ]
.RI [ boolean ]
.
.SH "DESCRIPTION"
.B getsebool
reports whether a particular SELinux boolean, or all SELinux booleans, are on or off.
In certain situations a boolean can be in one state with a pending
change to the other state. getsebool will report this as a pending change.
The pending value indicates
the value that will be applied upon the next boolean commit.

The setting of boolean values occurs in two stages; first the pending
value is changed, then the booleans are committed, causing their
active values to become their pending values. This allows a group of
booleans to be changed in a single transaction, by setting all of
their pending values as desired and then committing once.
.
.SH OPTIONS
.TP
.B \-a
Show all SELinux booleans.
.
.SH EXAMPLE
.nf
Show current state of httpd_can_connect_ftp
# getsebool httpd_can_connect_ftp
.
.SH AUTHOR
This manual page was written by Dan Walsh <dwalsh@redhat.com>.
The program was written by Tresys Technology.
.
.SH "SEE ALSO"
.BR selinux (8),
.BR setsebool (8),
.BR booleans (8)
