.TH "matchpathcon" "8" "21 April 2005" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
matchpathcon \- get the default SELinux security context for the specified path from the file contexts configuration.

.SH "SYNOPSIS"
.B matchpathcon [-V] [-N] [-n] [-f file_contexts_file ] [-p prefix ] filepath...
.SH "DESCRIPTION"
.B matchpathcon
queries the system policy and outputs the default security context associated with the filepath.

Note: Identical paths can have different security contexts, depending on the file type. (regular file, directory, link file, char file ...)

.B matchpathcon 
will also take the file type into consideration in determining the default security context if the file exists.  If the file does not exist, no file type matching will occur.

.SH OPTIONS
.B \-n
Do not display path.

.B \-N
Do not use translations.

.B \-f file_context_file
Use alternate file_context file

.B \-p prefix
Use prefix to speed translations

.B \-V
Verify file context on disk matches defaults

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
.BR selinux "(8), "
.BR matchpathcon "(3), " 
