.TH "sefcontext_compile" "8" "12 Aug 2015" "dwalsh@redhat.com" "SELinux Command Line documentation"
.SH "NAME"
sefcontext_compile \- compile file context regular expression files
.
.SH "SYNOPSIS"
.B sefcontext_compile
.RB [ \-o
.IR outputfile ]
.RB [ \-p
.IR policyfile ]
.I inputfile
.
.SH "DESCRIPTION"
.B sefcontext_compile
is used to compile file context regular expressions into
.BR pcre (3)
format.
.sp
The compiled file is used by libselinux file labeling functions.
.sp
By default
.B sefcontext_compile
writes the compiled pcre file with the
.B .bin
suffix appended (e.g. \fIinputfile\fB.bin\fR).
.SH OPTIONS
.TP
.B \-o
Specify an
.I outputfile
that must be a fully qualified file name as the
.B .bin
suffix is not automatically added.
.TP
.B \-p
Specify a binary
.I policyfile
that will be used to validate the context entries in the
.I inputfile
.br
If an invalid context is found the pcre formatted file will not be written and
an error will be returned.

.SH "RETURN VALUE"
On error -1 is returned.  On success 0 is returned.

.SH "EXAMPLES"
.B Example 1:
.br
sefcontext_compile /etc/selinux/targeted/contexts/files/file_contexts
.sp
Results in the following file being generated:
.RS
/etc/selinux/targeted/contexts/files/file_contexts.bin
.RE
.sp
.B Example 2:
.br
sefcontext_compile -o new_fc.bin /etc/selinux/targeted/contexts/files/file_contexts
.sp
Results in the following file being generated in the cwd:
.RS
new_fc.bin
.RE
.
.SH AUTHOR
Dan Walsh, <dwalsh@redhat.com>
.
.SH "SEE ALSO"
.BR selinux (8),
.BR semanage (8),
