.TH "setsebool" "8" "11 августа 2004" "dwalsh@redhat.com" "Документация по командной строке SELinux"
.SH "ИМЯ"
setsebool \- установить значение логического переключателя SELinux

.SH "ОБЗОР"
.B setsebool
.I "[ \-PNV ] boolean value | bool1=val1 bool2=val2 ..."

.SH "ОПИСАНИЕ"
.B setsebool 
устанавливает текущее состояние отдельного логического переключателя SELinux или списка логических переключателей в указанное значение. Это значение может быть либо 1, true или on (включает логический переключатель), либо 0, false или off (отключает логический переключатель). 

Если параметр \-P не указан, будет изменено только текущее значение логического переключателя; параметры загрузки по умолчанию останутся без изменений. 

Если параметр \-P указан, все ожидающие значения записываются в файл политики на диске. Поэтому они не будут сбрасываться после перезагрузок.

Если параметр \-N указан, политика на диске не перезагружается в ядро.

Если параметр \-V указан, показываются подробные сообщения об ошибках из библиотек semanage.

.SH "СМОТРИТЕ ТАКЖЕ"
getsebool(8), booleans(8), togglesebool(8), semanage(8)

.SH АВТОРЫ
Эта страница руководства была написана Dan Walsh <dwalsh@redhat.com>.
Программа была написана Tresys Technology.
Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
