.TH semanage_set_root 3 "1 June 2011" "dwalsh@redhat.com" "Libsemanage API documentation"

.SH "NAME"
semanage_set_root \- SELinux Management API

.SH "SYNOPSIS"
Set the alternate root directory for SELinux configuration directory.

.B	#include <semanage/handle.h>

.B	extern const char *semanage_set_root(const char *path);

.SH "DESCRIPTION"
.TP
This function sets an alternate root directory to for SELinux configuration paths to be used by the semanage library.

.SH "RETURN VALUE"
In case of failure, \-1 is returned.
Otherwise 0 is returned.

.SH "SEE ALSO"
.BR semanage_handle_create "(3), " semanage_connect "(3), "
