.TH RUN_INIT "8" "May 2003" "Security Enhanced Linux"
.SH NAME
run_init \- run an init script in the proper SELinux context
.SH SYNOPSIS
.B run_init 
\fISCRIPT\fR [[\fIARGS\fR]...] 
.br
.SH DESCRIPTION
.PP
Run a init script under the proper context, which is specified in 
/etc/selinux/POLICYTYPE/contexts/initrc_context.
It is generally used interactively as it requires either shadow or
PAM user authentication (depending on compile-time options).  It
should be possible to configure PAM such that interactive input is
not required.  Check your PAM documentation.
.SH FILES
/etc/passwd - user account information
.br
/etc/shadow - encrypted passwords and age information
.br
/etc/selinux/POLICYTYPE/contexts/initrc_context - contains the context to run init scripts under
.SH SEE ALSO
.BR newrole (1),
.BR runcon (1)
.SH AUTHORS
.nf
Wayne Salamon (wsalamon@tislabs.com) 
Dan Walsh (dwalsh@redhat.com) 
