.TH RUN_INIT "8" "May 2003" "Security Enhanced Linux"
.SH NAME
run_init \- run an init script in the proper SELinux context
.SH SYNOPSIS
.B run_init 
\fISCRIPT\fR [[\fIARGS\fR]...] 
.br
.SH DESCRIPTION
.PP
Run a init script under the proper context, which is specified in
.IR {/etc,/usr/lib}/selinux/{SELINUXTYPE}/contexts/initrc_context .
It is generally used interactively as it requires either shadow or
PAM user authentication (depending on compile-time options).  It
should be possible to configure PAM such that interactive input is
not required.  Check your PAM documentation.
.SH FILES
.TP
.I /etc/passwd
User account information
.TP
.I /etc/shadow
Encrypted passwords and age information
.TP
.I /etc/selinux/{SELINUXTYPE}/contexts/initrc_context
.TP
.I /usr/lib/selinux/{SELINUXTYPE}/contexts/initrc_context
Contains the context to run init scripts under. The file in
.B /etc
overrides the default configuration provided by the vendor in
.BR /usr/lib .
.SH SEE ALSO
.BR newrole (1),
.BR runcon (1)
.SH AUTHORS
.nf
Wayne Salamon (wsalamon@tislabs.com) 
Dan Walsh (dwalsh@redhat.com) 
