.TH "selinux-polgengui" "8" "8 April 2013" "System Config Tools Manual" "System Config Tools Manual"

.SH NAME
selinux\-polgengui \- SELinux Policy Generation Tool

.SH SYNOPSIS
.B selinux-polgengui

.SH DESCRIPTION
\fBselinux-polgengui\fP is a graphical tool, which can be used to create a framework for building SELinux Policy.
.SH OPTIONS
None

.SH FILES
\fi/usr/bin/selinux-polgengui\fP

.SH Examples
To run the program type:

selinux-polgengui

.PP
.SH "SEE ALSO"
.TP
selinux(1), sepolicy(8), sepolicy-generate(8)
.PP

.SH REPORTING BUGS
Report bugs to <http://bugzilla.redhat.com>.

.SH LICENSE AND AUTHORS
\fBselinux-polgengui\fP is licensed under the GNU General Public License and
is copyrighted by Red Hat, Inc.
.br
This man page was written by Daniel Walsh <dwalsh@redhat.com>
