.TH "system-config-selinux" "8" "8 April 2013" "System Config Tools Manual" "System Config Tools Manual"

.SH NAME
system\-config\-selinux \- SELinux Management tool

.SH SYNOPSIS
.B system-config-selinux

.SH DESCRIPTION
\fBsystem-config-selinux\fP provides a graphical interface for managing the
SELinux configuration.

.SH OPTIONS
None

.SH FILES
\fi/usr/bin/system-config-selinux\fP

.SH Examples
To run the program type:

system-config-selinux

.PP
.SH "SEE ALSO"
.TP
selinux(1), semanage(8)
.PP

.SH REPORTING BUGS
Report bugs to <http://bugzilla.redhat.com>.

.SH LICENSE AND AUTHORS
\fBsystem-config-selinux\fP is licensed under the GNU General Public License and
is copyrighted by Red Hat, Inc.
.br
This man page was written by Daniel Walsh <dwalsh@redhat.com>
