# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_semanage', [dirname(__file__)])
        except ImportError:
            import _semanage
            return _semanage
        if fp is not None:
            try:
                _mod = imp.load_module('_semanage', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _semanage = swig_import_helper()
    del swig_import_helper
else:
    import _semanage
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


SEMANAGE_MSG_ERR = _semanage.SEMANAGE_MSG_ERR
SEMANAGE_MSG_WARN = _semanage.SEMANAGE_MSG_WARN
SEMANAGE_MSG_INFO = _semanage.SEMANAGE_MSG_INFO

def semanage_msg_get_level(*args):
  return _semanage.semanage_msg_get_level(*args)
semanage_msg_get_level = _semanage.semanage_msg_get_level

def semanage_msg_get_channel(*args):
  return _semanage.semanage_msg_get_channel(*args)
semanage_msg_get_channel = _semanage.semanage_msg_get_channel

def semanage_msg_get_fname(*args):
  return _semanage.semanage_msg_get_fname(*args)
semanage_msg_get_fname = _semanage.semanage_msg_get_fname

def semanage_msg_set_callback(*args):
  return _semanage.semanage_msg_set_callback(*args)
semanage_msg_set_callback = _semanage.semanage_msg_set_callback

def semanage_handle_create():
  return _semanage.semanage_handle_create()
semanage_handle_create = _semanage.semanage_handle_create

def semanage_handle_destroy(*args):
  return _semanage.semanage_handle_destroy(*args)
semanage_handle_destroy = _semanage.semanage_handle_destroy
SEMANAGE_CON_INVALID = _semanage.SEMANAGE_CON_INVALID
SEMANAGE_CON_DIRECT = _semanage.SEMANAGE_CON_DIRECT
SEMANAGE_CON_POLSERV_LOCAL = _semanage.SEMANAGE_CON_POLSERV_LOCAL
SEMANAGE_CON_POLSERV_REMOTE = _semanage.SEMANAGE_CON_POLSERV_REMOTE

def semanage_select_store(*args):
  return _semanage.semanage_select_store(*args)
semanage_select_store = _semanage.semanage_select_store

def semanage_reload_policy(*args):
  return _semanage.semanage_reload_policy(*args)
semanage_reload_policy = _semanage.semanage_reload_policy

def semanage_set_reload(*args):
  return _semanage.semanage_set_reload(*args)
semanage_set_reload = _semanage.semanage_set_reload

def semanage_set_rebuild(*args):
  return _semanage.semanage_set_rebuild(*args)
semanage_set_rebuild = _semanage.semanage_set_rebuild

def semanage_set_create_store(*args):
  return _semanage.semanage_set_create_store(*args)
semanage_set_create_store = _semanage.semanage_set_create_store

def semanage_get_disable_dontaudit(*args):
  return _semanage.semanage_get_disable_dontaudit(*args)
semanage_get_disable_dontaudit = _semanage.semanage_get_disable_dontaudit

def semanage_set_disable_dontaudit(*args):
  return _semanage.semanage_set_disable_dontaudit(*args)
semanage_set_disable_dontaudit = _semanage.semanage_set_disable_dontaudit

def semanage_set_check_contexts(*args):
  return _semanage.semanage_set_check_contexts(*args)
semanage_set_check_contexts = _semanage.semanage_set_check_contexts

def semanage_is_managed(*args):
  return _semanage.semanage_is_managed(*args)
semanage_is_managed = _semanage.semanage_is_managed

def semanage_connect(*args):
  return _semanage.semanage_connect(*args)
semanage_connect = _semanage.semanage_connect

def semanage_disconnect(*args):
  return _semanage.semanage_disconnect(*args)
semanage_disconnect = _semanage.semanage_disconnect

def semanage_begin_transaction(*args):
  return _semanage.semanage_begin_transaction(*args)
semanage_begin_transaction = _semanage.semanage_begin_transaction

def semanage_commit(*args):
  return _semanage.semanage_commit(*args)
semanage_commit = _semanage.semanage_commit
SEMANAGE_CAN_READ = _semanage.SEMANAGE_CAN_READ
SEMANAGE_CAN_WRITE = _semanage.SEMANAGE_CAN_WRITE

def semanage_access_check(*args):
  return _semanage.semanage_access_check(*args)
semanage_access_check = _semanage.semanage_access_check

def semanage_is_connected(*args):
  return _semanage.semanage_is_connected(*args)
semanage_is_connected = _semanage.semanage_is_connected

def semanage_mls_enabled(*args):
  return _semanage.semanage_mls_enabled(*args)
semanage_mls_enabled = _semanage.semanage_mls_enabled

def semanage_module_install(*args):
  return _semanage.semanage_module_install(*args)
semanage_module_install = _semanage.semanage_module_install

def semanage_module_install_file(*args):
  return _semanage.semanage_module_install_file(*args)
semanage_module_install_file = _semanage.semanage_module_install_file

def semanage_module_upgrade(*args):
  return _semanage.semanage_module_upgrade(*args)
semanage_module_upgrade = _semanage.semanage_module_upgrade

def semanage_module_upgrade_file(*args):
  return _semanage.semanage_module_upgrade_file(*args)
semanage_module_upgrade_file = _semanage.semanage_module_upgrade_file

def semanage_module_install_base(*args):
  return _semanage.semanage_module_install_base(*args)
semanage_module_install_base = _semanage.semanage_module_install_base

def semanage_module_install_base_file(*args):
  return _semanage.semanage_module_install_base_file(*args)
semanage_module_install_base_file = _semanage.semanage_module_install_base_file

def semanage_module_enable(*args):
  return _semanage.semanage_module_enable(*args)
semanage_module_enable = _semanage.semanage_module_enable

def semanage_module_disable(*args):
  return _semanage.semanage_module_disable(*args)
semanage_module_disable = _semanage.semanage_module_disable

def semanage_module_remove(*args):
  return _semanage.semanage_module_remove(*args)
semanage_module_remove = _semanage.semanage_module_remove

def semanage_module_list(*args):
  return _semanage.semanage_module_list(*args)
semanage_module_list = _semanage.semanage_module_list

def semanage_module_info_datum_destroy(*args):
  return _semanage.semanage_module_info_datum_destroy(*args)
semanage_module_info_datum_destroy = _semanage.semanage_module_info_datum_destroy

def semanage_module_list_nth(*args):
  return _semanage.semanage_module_list_nth(*args)
semanage_module_list_nth = _semanage.semanage_module_list_nth

def semanage_module_get_name(*args):
  return _semanage.semanage_module_get_name(*args)
semanage_module_get_name = _semanage.semanage_module_get_name

def semanage_module_get_version(*args):
  return _semanage.semanage_module_get_version(*args)
semanage_module_get_version = _semanage.semanage_module_get_version

def semanage_module_get_enabled(*args):
  return _semanage.semanage_module_get_enabled(*args)
semanage_module_get_enabled = _semanage.semanage_module_get_enabled

def semanage_context_get_user(*args):
  return _semanage.semanage_context_get_user(*args)
semanage_context_get_user = _semanage.semanage_context_get_user

def semanage_context_set_user(*args):
  return _semanage.semanage_context_set_user(*args)
semanage_context_set_user = _semanage.semanage_context_set_user

def semanage_context_get_role(*args):
  return _semanage.semanage_context_get_role(*args)
semanage_context_get_role = _semanage.semanage_context_get_role

def semanage_context_set_role(*args):
  return _semanage.semanage_context_set_role(*args)
semanage_context_set_role = _semanage.semanage_context_set_role

def semanage_context_get_type(*args):
  return _semanage.semanage_context_get_type(*args)
semanage_context_get_type = _semanage.semanage_context_get_type

def semanage_context_set_type(*args):
  return _semanage.semanage_context_set_type(*args)
semanage_context_set_type = _semanage.semanage_context_set_type

def semanage_context_get_mls(*args):
  return _semanage.semanage_context_get_mls(*args)
semanage_context_get_mls = _semanage.semanage_context_get_mls

def semanage_context_set_mls(*args):
  return _semanage.semanage_context_set_mls(*args)
semanage_context_set_mls = _semanage.semanage_context_set_mls

def semanage_context_create(*args):
  return _semanage.semanage_context_create(*args)
semanage_context_create = _semanage.semanage_context_create

def semanage_context_clone(*args):
  return _semanage.semanage_context_clone(*args)
semanage_context_clone = _semanage.semanage_context_clone

def semanage_context_free(*args):
  return _semanage.semanage_context_free(*args)
semanage_context_free = _semanage.semanage_context_free

def semanage_context_from_string(*args):
  return _semanage.semanage_context_from_string(*args)
semanage_context_from_string = _semanage.semanage_context_from_string

def semanage_context_to_string(*args):
  return _semanage.semanage_context_to_string(*args)
semanage_context_to_string = _semanage.semanage_context_to_string

def semanage_bool_key_create(*args):
  return _semanage.semanage_bool_key_create(*args)
semanage_bool_key_create = _semanage.semanage_bool_key_create

def semanage_bool_key_extract(*args):
  return _semanage.semanage_bool_key_extract(*args)
semanage_bool_key_extract = _semanage.semanage_bool_key_extract

def semanage_bool_key_free(*args):
  return _semanage.semanage_bool_key_free(*args)
semanage_bool_key_free = _semanage.semanage_bool_key_free

def semanage_bool_compare(*args):
  return _semanage.semanage_bool_compare(*args)
semanage_bool_compare = _semanage.semanage_bool_compare

def semanage_bool_compare2(*args):
  return _semanage.semanage_bool_compare2(*args)
semanage_bool_compare2 = _semanage.semanage_bool_compare2

def semanage_bool_get_name(*args):
  return _semanage.semanage_bool_get_name(*args)
semanage_bool_get_name = _semanage.semanage_bool_get_name

def semanage_bool_set_name(*args):
  return _semanage.semanage_bool_set_name(*args)
semanage_bool_set_name = _semanage.semanage_bool_set_name

def semanage_bool_get_value(*args):
  return _semanage.semanage_bool_get_value(*args)
semanage_bool_get_value = _semanage.semanage_bool_get_value

def semanage_bool_set_value(*args):
  return _semanage.semanage_bool_set_value(*args)
semanage_bool_set_value = _semanage.semanage_bool_set_value

def semanage_bool_create(*args):
  return _semanage.semanage_bool_create(*args)
semanage_bool_create = _semanage.semanage_bool_create

def semanage_bool_clone(*args):
  return _semanage.semanage_bool_clone(*args)
semanage_bool_clone = _semanage.semanage_bool_clone

def semanage_bool_free(*args):
  return _semanage.semanage_bool_free(*args)
semanage_bool_free = _semanage.semanage_bool_free

def semanage_bool_query(*args):
  return _semanage.semanage_bool_query(*args)
semanage_bool_query = _semanage.semanage_bool_query

def semanage_bool_exists(*args):
  return _semanage.semanage_bool_exists(*args)
semanage_bool_exists = _semanage.semanage_bool_exists

def semanage_bool_count(*args):
  return _semanage.semanage_bool_count(*args)
semanage_bool_count = _semanage.semanage_bool_count

def semanage_bool_iterate(*args):
  return _semanage.semanage_bool_iterate(*args)
semanage_bool_iterate = _semanage.semanage_bool_iterate

def semanage_bool_list(*args):
  return _semanage.semanage_bool_list(*args)
semanage_bool_list = _semanage.semanage_bool_list

def semanage_bool_modify_local(*args):
  return _semanage.semanage_bool_modify_local(*args)
semanage_bool_modify_local = _semanage.semanage_bool_modify_local

def semanage_bool_del_local(*args):
  return _semanage.semanage_bool_del_local(*args)
semanage_bool_del_local = _semanage.semanage_bool_del_local

def semanage_bool_query_local(*args):
  return _semanage.semanage_bool_query_local(*args)
semanage_bool_query_local = _semanage.semanage_bool_query_local

def semanage_bool_exists_local(*args):
  return _semanage.semanage_bool_exists_local(*args)
semanage_bool_exists_local = _semanage.semanage_bool_exists_local

def semanage_bool_count_local(*args):
  return _semanage.semanage_bool_count_local(*args)
semanage_bool_count_local = _semanage.semanage_bool_count_local

def semanage_bool_iterate_local(*args):
  return _semanage.semanage_bool_iterate_local(*args)
semanage_bool_iterate_local = _semanage.semanage_bool_iterate_local

def semanage_bool_list_local(*args):
  return _semanage.semanage_bool_list_local(*args)
semanage_bool_list_local = _semanage.semanage_bool_list_local

def semanage_bool_set_active(*args):
  return _semanage.semanage_bool_set_active(*args)
semanage_bool_set_active = _semanage.semanage_bool_set_active

def semanage_bool_query_active(*args):
  return _semanage.semanage_bool_query_active(*args)
semanage_bool_query_active = _semanage.semanage_bool_query_active

def semanage_bool_exists_active(*args):
  return _semanage.semanage_bool_exists_active(*args)
semanage_bool_exists_active = _semanage.semanage_bool_exists_active

def semanage_bool_count_active(*args):
  return _semanage.semanage_bool_count_active(*args)
semanage_bool_count_active = _semanage.semanage_bool_count_active

def semanage_bool_iterate_active(*args):
  return _semanage.semanage_bool_iterate_active(*args)
semanage_bool_iterate_active = _semanage.semanage_bool_iterate_active

def semanage_bool_list_active(*args):
  return _semanage.semanage_bool_list_active(*args)
semanage_bool_list_active = _semanage.semanage_bool_list_active

def semanage_iface_compare(*args):
  return _semanage.semanage_iface_compare(*args)
semanage_iface_compare = _semanage.semanage_iface_compare

def semanage_iface_compare2(*args):
  return _semanage.semanage_iface_compare2(*args)
semanage_iface_compare2 = _semanage.semanage_iface_compare2

def semanage_iface_key_create(*args):
  return _semanage.semanage_iface_key_create(*args)
semanage_iface_key_create = _semanage.semanage_iface_key_create

def semanage_iface_key_extract(*args):
  return _semanage.semanage_iface_key_extract(*args)
semanage_iface_key_extract = _semanage.semanage_iface_key_extract

def semanage_iface_key_free(*args):
  return _semanage.semanage_iface_key_free(*args)
semanage_iface_key_free = _semanage.semanage_iface_key_free

def semanage_iface_get_name(*args):
  return _semanage.semanage_iface_get_name(*args)
semanage_iface_get_name = _semanage.semanage_iface_get_name

def semanage_iface_set_name(*args):
  return _semanage.semanage_iface_set_name(*args)
semanage_iface_set_name = _semanage.semanage_iface_set_name

def semanage_iface_get_ifcon(*args):
  return _semanage.semanage_iface_get_ifcon(*args)
semanage_iface_get_ifcon = _semanage.semanage_iface_get_ifcon

def semanage_iface_set_ifcon(*args):
  return _semanage.semanage_iface_set_ifcon(*args)
semanage_iface_set_ifcon = _semanage.semanage_iface_set_ifcon

def semanage_iface_get_msgcon(*args):
  return _semanage.semanage_iface_get_msgcon(*args)
semanage_iface_get_msgcon = _semanage.semanage_iface_get_msgcon

def semanage_iface_set_msgcon(*args):
  return _semanage.semanage_iface_set_msgcon(*args)
semanage_iface_set_msgcon = _semanage.semanage_iface_set_msgcon

def semanage_iface_create(*args):
  return _semanage.semanage_iface_create(*args)
semanage_iface_create = _semanage.semanage_iface_create

def semanage_iface_clone(*args):
  return _semanage.semanage_iface_clone(*args)
semanage_iface_clone = _semanage.semanage_iface_clone

def semanage_iface_free(*args):
  return _semanage.semanage_iface_free(*args)
semanage_iface_free = _semanage.semanage_iface_free

def semanage_iface_modify_local(*args):
  return _semanage.semanage_iface_modify_local(*args)
semanage_iface_modify_local = _semanage.semanage_iface_modify_local

def semanage_iface_del_local(*args):
  return _semanage.semanage_iface_del_local(*args)
semanage_iface_del_local = _semanage.semanage_iface_del_local

def semanage_iface_query_local(*args):
  return _semanage.semanage_iface_query_local(*args)
semanage_iface_query_local = _semanage.semanage_iface_query_local

def semanage_iface_exists_local(*args):
  return _semanage.semanage_iface_exists_local(*args)
semanage_iface_exists_local = _semanage.semanage_iface_exists_local

def semanage_iface_count_local(*args):
  return _semanage.semanage_iface_count_local(*args)
semanage_iface_count_local = _semanage.semanage_iface_count_local

def semanage_iface_iterate_local(*args):
  return _semanage.semanage_iface_iterate_local(*args)
semanage_iface_iterate_local = _semanage.semanage_iface_iterate_local

def semanage_iface_list_local(*args):
  return _semanage.semanage_iface_list_local(*args)
semanage_iface_list_local = _semanage.semanage_iface_list_local

def semanage_iface_query(*args):
  return _semanage.semanage_iface_query(*args)
semanage_iface_query = _semanage.semanage_iface_query

def semanage_iface_exists(*args):
  return _semanage.semanage_iface_exists(*args)
semanage_iface_exists = _semanage.semanage_iface_exists

def semanage_iface_count(*args):
  return _semanage.semanage_iface_count(*args)
semanage_iface_count = _semanage.semanage_iface_count

def semanage_iface_iterate(*args):
  return _semanage.semanage_iface_iterate(*args)
semanage_iface_iterate = _semanage.semanage_iface_iterate

def semanage_iface_list(*args):
  return _semanage.semanage_iface_list(*args)
semanage_iface_list = _semanage.semanage_iface_list

def semanage_user_key_create(*args):
  return _semanage.semanage_user_key_create(*args)
semanage_user_key_create = _semanage.semanage_user_key_create

def semanage_user_key_extract(*args):
  return _semanage.semanage_user_key_extract(*args)
semanage_user_key_extract = _semanage.semanage_user_key_extract

def semanage_user_key_free(*args):
  return _semanage.semanage_user_key_free(*args)
semanage_user_key_free = _semanage.semanage_user_key_free

def semanage_user_compare(*args):
  return _semanage.semanage_user_compare(*args)
semanage_user_compare = _semanage.semanage_user_compare

def semanage_user_compare2(*args):
  return _semanage.semanage_user_compare2(*args)
semanage_user_compare2 = _semanage.semanage_user_compare2

def semanage_user_get_name(*args):
  return _semanage.semanage_user_get_name(*args)
semanage_user_get_name = _semanage.semanage_user_get_name

def semanage_user_set_name(*args):
  return _semanage.semanage_user_set_name(*args)
semanage_user_set_name = _semanage.semanage_user_set_name

def semanage_user_get_prefix(*args):
  return _semanage.semanage_user_get_prefix(*args)
semanage_user_get_prefix = _semanage.semanage_user_get_prefix

def semanage_user_set_prefix(*args):
  return _semanage.semanage_user_set_prefix(*args)
semanage_user_set_prefix = _semanage.semanage_user_set_prefix

def semanage_user_get_mlslevel(*args):
  return _semanage.semanage_user_get_mlslevel(*args)
semanage_user_get_mlslevel = _semanage.semanage_user_get_mlslevel

def semanage_user_set_mlslevel(*args):
  return _semanage.semanage_user_set_mlslevel(*args)
semanage_user_set_mlslevel = _semanage.semanage_user_set_mlslevel

def semanage_user_get_mlsrange(*args):
  return _semanage.semanage_user_get_mlsrange(*args)
semanage_user_get_mlsrange = _semanage.semanage_user_get_mlsrange

def semanage_user_set_mlsrange(*args):
  return _semanage.semanage_user_set_mlsrange(*args)
semanage_user_set_mlsrange = _semanage.semanage_user_set_mlsrange

def semanage_user_get_num_roles(*args):
  return _semanage.semanage_user_get_num_roles(*args)
semanage_user_get_num_roles = _semanage.semanage_user_get_num_roles

def semanage_user_add_role(*args):
  return _semanage.semanage_user_add_role(*args)
semanage_user_add_role = _semanage.semanage_user_add_role

def semanage_user_del_role(*args):
  return _semanage.semanage_user_del_role(*args)
semanage_user_del_role = _semanage.semanage_user_del_role

def semanage_user_has_role(*args):
  return _semanage.semanage_user_has_role(*args)
semanage_user_has_role = _semanage.semanage_user_has_role

def semanage_user_get_roles(*args):
  return _semanage.semanage_user_get_roles(*args)
semanage_user_get_roles = _semanage.semanage_user_get_roles

def semanage_user_set_roles(*args):
  return _semanage.semanage_user_set_roles(*args)
semanage_user_set_roles = _semanage.semanage_user_set_roles

def semanage_user_create(*args):
  return _semanage.semanage_user_create(*args)
semanage_user_create = _semanage.semanage_user_create

def semanage_user_clone(*args):
  return _semanage.semanage_user_clone(*args)
semanage_user_clone = _semanage.semanage_user_clone

def semanage_user_free(*args):
  return _semanage.semanage_user_free(*args)
semanage_user_free = _semanage.semanage_user_free

def semanage_user_modify_local(*args):
  return _semanage.semanage_user_modify_local(*args)
semanage_user_modify_local = _semanage.semanage_user_modify_local

def semanage_user_del_local(*args):
  return _semanage.semanage_user_del_local(*args)
semanage_user_del_local = _semanage.semanage_user_del_local

def semanage_user_query_local(*args):
  return _semanage.semanage_user_query_local(*args)
semanage_user_query_local = _semanage.semanage_user_query_local

def semanage_user_exists_local(*args):
  return _semanage.semanage_user_exists_local(*args)
semanage_user_exists_local = _semanage.semanage_user_exists_local

def semanage_user_count_local(*args):
  return _semanage.semanage_user_count_local(*args)
semanage_user_count_local = _semanage.semanage_user_count_local

def semanage_user_iterate_local(*args):
  return _semanage.semanage_user_iterate_local(*args)
semanage_user_iterate_local = _semanage.semanage_user_iterate_local

def semanage_user_list_local(*args):
  return _semanage.semanage_user_list_local(*args)
semanage_user_list_local = _semanage.semanage_user_list_local

def semanage_user_query(*args):
  return _semanage.semanage_user_query(*args)
semanage_user_query = _semanage.semanage_user_query

def semanage_user_exists(*args):
  return _semanage.semanage_user_exists(*args)
semanage_user_exists = _semanage.semanage_user_exists

def semanage_user_count(*args):
  return _semanage.semanage_user_count(*args)
semanage_user_count = _semanage.semanage_user_count

def semanage_user_iterate(*args):
  return _semanage.semanage_user_iterate(*args)
semanage_user_iterate = _semanage.semanage_user_iterate

def semanage_user_list(*args):
  return _semanage.semanage_user_list(*args)
semanage_user_list = _semanage.semanage_user_list
SEMANAGE_PROTO_UDP = _semanage.SEMANAGE_PROTO_UDP
SEMANAGE_PROTO_TCP = _semanage.SEMANAGE_PROTO_TCP

def semanage_port_compare(*args):
  return _semanage.semanage_port_compare(*args)
semanage_port_compare = _semanage.semanage_port_compare

def semanage_port_compare2(*args):
  return _semanage.semanage_port_compare2(*args)
semanage_port_compare2 = _semanage.semanage_port_compare2

def semanage_port_key_create(*args):
  return _semanage.semanage_port_key_create(*args)
semanage_port_key_create = _semanage.semanage_port_key_create

def semanage_port_key_extract(*args):
  return _semanage.semanage_port_key_extract(*args)
semanage_port_key_extract = _semanage.semanage_port_key_extract

def semanage_port_key_free(*args):
  return _semanage.semanage_port_key_free(*args)
semanage_port_key_free = _semanage.semanage_port_key_free

def semanage_port_get_proto(*args):
  return _semanage.semanage_port_get_proto(*args)
semanage_port_get_proto = _semanage.semanage_port_get_proto

def semanage_port_set_proto(*args):
  return _semanage.semanage_port_set_proto(*args)
semanage_port_set_proto = _semanage.semanage_port_set_proto

def semanage_port_get_proto_str(*args):
  return _semanage.semanage_port_get_proto_str(*args)
semanage_port_get_proto_str = _semanage.semanage_port_get_proto_str

def semanage_port_get_low(*args):
  return _semanage.semanage_port_get_low(*args)
semanage_port_get_low = _semanage.semanage_port_get_low

def semanage_port_get_high(*args):
  return _semanage.semanage_port_get_high(*args)
semanage_port_get_high = _semanage.semanage_port_get_high

def semanage_port_set_port(*args):
  return _semanage.semanage_port_set_port(*args)
semanage_port_set_port = _semanage.semanage_port_set_port

def semanage_port_set_range(*args):
  return _semanage.semanage_port_set_range(*args)
semanage_port_set_range = _semanage.semanage_port_set_range

def semanage_port_get_con(*args):
  return _semanage.semanage_port_get_con(*args)
semanage_port_get_con = _semanage.semanage_port_get_con

def semanage_port_set_con(*args):
  return _semanage.semanage_port_set_con(*args)
semanage_port_set_con = _semanage.semanage_port_set_con

def semanage_port_create(*args):
  return _semanage.semanage_port_create(*args)
semanage_port_create = _semanage.semanage_port_create

def semanage_port_clone(*args):
  return _semanage.semanage_port_clone(*args)
semanage_port_clone = _semanage.semanage_port_clone

def semanage_port_free(*args):
  return _semanage.semanage_port_free(*args)
semanage_port_free = _semanage.semanage_port_free

def semanage_port_modify_local(*args):
  return _semanage.semanage_port_modify_local(*args)
semanage_port_modify_local = _semanage.semanage_port_modify_local

def semanage_port_del_local(*args):
  return _semanage.semanage_port_del_local(*args)
semanage_port_del_local = _semanage.semanage_port_del_local

def semanage_port_query_local(*args):
  return _semanage.semanage_port_query_local(*args)
semanage_port_query_local = _semanage.semanage_port_query_local

def semanage_port_exists_local(*args):
  return _semanage.semanage_port_exists_local(*args)
semanage_port_exists_local = _semanage.semanage_port_exists_local

def semanage_port_count_local(*args):
  return _semanage.semanage_port_count_local(*args)
semanage_port_count_local = _semanage.semanage_port_count_local

def semanage_port_iterate_local(*args):
  return _semanage.semanage_port_iterate_local(*args)
semanage_port_iterate_local = _semanage.semanage_port_iterate_local

def semanage_port_list_local(*args):
  return _semanage.semanage_port_list_local(*args)
semanage_port_list_local = _semanage.semanage_port_list_local

def semanage_port_query(*args):
  return _semanage.semanage_port_query(*args)
semanage_port_query = _semanage.semanage_port_query

def semanage_port_exists(*args):
  return _semanage.semanage_port_exists(*args)
semanage_port_exists = _semanage.semanage_port_exists

def semanage_port_count(*args):
  return _semanage.semanage_port_count(*args)
semanage_port_count = _semanage.semanage_port_count

def semanage_port_iterate(*args):
  return _semanage.semanage_port_iterate(*args)
semanage_port_iterate = _semanage.semanage_port_iterate

def semanage_port_list(*args):
  return _semanage.semanage_port_list(*args)
semanage_port_list = _semanage.semanage_port_list

def semanage_fcontext_compare(*args):
  return _semanage.semanage_fcontext_compare(*args)
semanage_fcontext_compare = _semanage.semanage_fcontext_compare

def semanage_fcontext_compare2(*args):
  return _semanage.semanage_fcontext_compare2(*args)
semanage_fcontext_compare2 = _semanage.semanage_fcontext_compare2

def semanage_fcontext_key_create(*args):
  return _semanage.semanage_fcontext_key_create(*args)
semanage_fcontext_key_create = _semanage.semanage_fcontext_key_create

def semanage_fcontext_key_extract(*args):
  return _semanage.semanage_fcontext_key_extract(*args)
semanage_fcontext_key_extract = _semanage.semanage_fcontext_key_extract

def semanage_fcontext_key_free(*args):
  return _semanage.semanage_fcontext_key_free(*args)
semanage_fcontext_key_free = _semanage.semanage_fcontext_key_free

def semanage_fcontext_get_expr(*args):
  return _semanage.semanage_fcontext_get_expr(*args)
semanage_fcontext_get_expr = _semanage.semanage_fcontext_get_expr

def semanage_fcontext_set_expr(*args):
  return _semanage.semanage_fcontext_set_expr(*args)
semanage_fcontext_set_expr = _semanage.semanage_fcontext_set_expr
SEMANAGE_FCONTEXT_ALL = _semanage.SEMANAGE_FCONTEXT_ALL
SEMANAGE_FCONTEXT_REG = _semanage.SEMANAGE_FCONTEXT_REG
SEMANAGE_FCONTEXT_DIR = _semanage.SEMANAGE_FCONTEXT_DIR
SEMANAGE_FCONTEXT_CHAR = _semanage.SEMANAGE_FCONTEXT_CHAR
SEMANAGE_FCONTEXT_BLOCK = _semanage.SEMANAGE_FCONTEXT_BLOCK
SEMANAGE_FCONTEXT_SOCK = _semanage.SEMANAGE_FCONTEXT_SOCK
SEMANAGE_FCONTEXT_LINK = _semanage.SEMANAGE_FCONTEXT_LINK
SEMANAGE_FCONTEXT_PIPE = _semanage.SEMANAGE_FCONTEXT_PIPE

def semanage_fcontext_get_type(*args):
  return _semanage.semanage_fcontext_get_type(*args)
semanage_fcontext_get_type = _semanage.semanage_fcontext_get_type

def semanage_fcontext_get_type_str(*args):
  return _semanage.semanage_fcontext_get_type_str(*args)
semanage_fcontext_get_type_str = _semanage.semanage_fcontext_get_type_str

def semanage_fcontext_set_type(*args):
  return _semanage.semanage_fcontext_set_type(*args)
semanage_fcontext_set_type = _semanage.semanage_fcontext_set_type

def semanage_fcontext_get_con(*args):
  return _semanage.semanage_fcontext_get_con(*args)
semanage_fcontext_get_con = _semanage.semanage_fcontext_get_con

def semanage_fcontext_set_con(*args):
  return _semanage.semanage_fcontext_set_con(*args)
semanage_fcontext_set_con = _semanage.semanage_fcontext_set_con

def semanage_fcontext_create(*args):
  return _semanage.semanage_fcontext_create(*args)
semanage_fcontext_create = _semanage.semanage_fcontext_create

def semanage_fcontext_clone(*args):
  return _semanage.semanage_fcontext_clone(*args)
semanage_fcontext_clone = _semanage.semanage_fcontext_clone

def semanage_fcontext_free(*args):
  return _semanage.semanage_fcontext_free(*args)
semanage_fcontext_free = _semanage.semanage_fcontext_free

def semanage_fcontext_modify_local(*args):
  return _semanage.semanage_fcontext_modify_local(*args)
semanage_fcontext_modify_local = _semanage.semanage_fcontext_modify_local

def semanage_fcontext_del_local(*args):
  return _semanage.semanage_fcontext_del_local(*args)
semanage_fcontext_del_local = _semanage.semanage_fcontext_del_local

def semanage_fcontext_query_local(*args):
  return _semanage.semanage_fcontext_query_local(*args)
semanage_fcontext_query_local = _semanage.semanage_fcontext_query_local

def semanage_fcontext_exists_local(*args):
  return _semanage.semanage_fcontext_exists_local(*args)
semanage_fcontext_exists_local = _semanage.semanage_fcontext_exists_local

def semanage_fcontext_count_local(*args):
  return _semanage.semanage_fcontext_count_local(*args)
semanage_fcontext_count_local = _semanage.semanage_fcontext_count_local

def semanage_fcontext_iterate_local(*args):
  return _semanage.semanage_fcontext_iterate_local(*args)
semanage_fcontext_iterate_local = _semanage.semanage_fcontext_iterate_local

def semanage_fcontext_list_local(*args):
  return _semanage.semanage_fcontext_list_local(*args)
semanage_fcontext_list_local = _semanage.semanage_fcontext_list_local

def semanage_fcontext_query(*args):
  return _semanage.semanage_fcontext_query(*args)
semanage_fcontext_query = _semanage.semanage_fcontext_query

def semanage_fcontext_exists(*args):
  return _semanage.semanage_fcontext_exists(*args)
semanage_fcontext_exists = _semanage.semanage_fcontext_exists

def semanage_fcontext_count(*args):
  return _semanage.semanage_fcontext_count(*args)
semanage_fcontext_count = _semanage.semanage_fcontext_count

def semanage_fcontext_iterate(*args):
  return _semanage.semanage_fcontext_iterate(*args)
semanage_fcontext_iterate = _semanage.semanage_fcontext_iterate

def semanage_fcontext_list(*args):
  return _semanage.semanage_fcontext_list(*args)
semanage_fcontext_list = _semanage.semanage_fcontext_list

def semanage_seuser_key_create(*args):
  return _semanage.semanage_seuser_key_create(*args)
semanage_seuser_key_create = _semanage.semanage_seuser_key_create

def semanage_seuser_key_extract(*args):
  return _semanage.semanage_seuser_key_extract(*args)
semanage_seuser_key_extract = _semanage.semanage_seuser_key_extract

def semanage_seuser_key_free(*args):
  return _semanage.semanage_seuser_key_free(*args)
semanage_seuser_key_free = _semanage.semanage_seuser_key_free

def semanage_seuser_compare(*args):
  return _semanage.semanage_seuser_compare(*args)
semanage_seuser_compare = _semanage.semanage_seuser_compare

def semanage_seuser_compare2(*args):
  return _semanage.semanage_seuser_compare2(*args)
semanage_seuser_compare2 = _semanage.semanage_seuser_compare2

def semanage_seuser_get_name(*args):
  return _semanage.semanage_seuser_get_name(*args)
semanage_seuser_get_name = _semanage.semanage_seuser_get_name

def semanage_seuser_set_name(*args):
  return _semanage.semanage_seuser_set_name(*args)
semanage_seuser_set_name = _semanage.semanage_seuser_set_name

def semanage_seuser_get_sename(*args):
  return _semanage.semanage_seuser_get_sename(*args)
semanage_seuser_get_sename = _semanage.semanage_seuser_get_sename

def semanage_seuser_set_sename(*args):
  return _semanage.semanage_seuser_set_sename(*args)
semanage_seuser_set_sename = _semanage.semanage_seuser_set_sename

def semanage_seuser_get_mlsrange(*args):
  return _semanage.semanage_seuser_get_mlsrange(*args)
semanage_seuser_get_mlsrange = _semanage.semanage_seuser_get_mlsrange

def semanage_seuser_set_mlsrange(*args):
  return _semanage.semanage_seuser_set_mlsrange(*args)
semanage_seuser_set_mlsrange = _semanage.semanage_seuser_set_mlsrange

def semanage_seuser_create(*args):
  return _semanage.semanage_seuser_create(*args)
semanage_seuser_create = _semanage.semanage_seuser_create

def semanage_seuser_clone(*args):
  return _semanage.semanage_seuser_clone(*args)
semanage_seuser_clone = _semanage.semanage_seuser_clone

def semanage_seuser_free(*args):
  return _semanage.semanage_seuser_free(*args)
semanage_seuser_free = _semanage.semanage_seuser_free

def semanage_seuser_modify_local(*args):
  return _semanage.semanage_seuser_modify_local(*args)
semanage_seuser_modify_local = _semanage.semanage_seuser_modify_local

def semanage_seuser_del_local(*args):
  return _semanage.semanage_seuser_del_local(*args)
semanage_seuser_del_local = _semanage.semanage_seuser_del_local

def semanage_seuser_query_local(*args):
  return _semanage.semanage_seuser_query_local(*args)
semanage_seuser_query_local = _semanage.semanage_seuser_query_local

def semanage_seuser_exists_local(*args):
  return _semanage.semanage_seuser_exists_local(*args)
semanage_seuser_exists_local = _semanage.semanage_seuser_exists_local

def semanage_seuser_count_local(*args):
  return _semanage.semanage_seuser_count_local(*args)
semanage_seuser_count_local = _semanage.semanage_seuser_count_local

def semanage_seuser_iterate_local(*args):
  return _semanage.semanage_seuser_iterate_local(*args)
semanage_seuser_iterate_local = _semanage.semanage_seuser_iterate_local

def semanage_seuser_list_local(*args):
  return _semanage.semanage_seuser_list_local(*args)
semanage_seuser_list_local = _semanage.semanage_seuser_list_local

def semanage_seuser_query(*args):
  return _semanage.semanage_seuser_query(*args)
semanage_seuser_query = _semanage.semanage_seuser_query

def semanage_seuser_exists(*args):
  return _semanage.semanage_seuser_exists(*args)
semanage_seuser_exists = _semanage.semanage_seuser_exists

def semanage_seuser_count(*args):
  return _semanage.semanage_seuser_count(*args)
semanage_seuser_count = _semanage.semanage_seuser_count

def semanage_seuser_iterate(*args):
  return _semanage.semanage_seuser_iterate(*args)
semanage_seuser_iterate = _semanage.semanage_seuser_iterate

def semanage_seuser_list(*args):
  return _semanage.semanage_seuser_list(*args)
semanage_seuser_list = _semanage.semanage_seuser_list
SEMANAGE_PROTO_IP4 = _semanage.SEMANAGE_PROTO_IP4
SEMANAGE_PROTO_IP6 = _semanage.SEMANAGE_PROTO_IP6

def semanage_node_compare(*args):
  return _semanage.semanage_node_compare(*args)
semanage_node_compare = _semanage.semanage_node_compare

def semanage_node_compare2(*args):
  return _semanage.semanage_node_compare2(*args)
semanage_node_compare2 = _semanage.semanage_node_compare2

def semanage_node_key_create(*args):
  return _semanage.semanage_node_key_create(*args)
semanage_node_key_create = _semanage.semanage_node_key_create

def semanage_node_key_extract(*args):
  return _semanage.semanage_node_key_extract(*args)
semanage_node_key_extract = _semanage.semanage_node_key_extract

def semanage_node_key_free(*args):
  return _semanage.semanage_node_key_free(*args)
semanage_node_key_free = _semanage.semanage_node_key_free

def semanage_node_get_addr(*args):
  return _semanage.semanage_node_get_addr(*args)
semanage_node_get_addr = _semanage.semanage_node_get_addr

def semanage_node_get_addr_bytes(*args):
  return _semanage.semanage_node_get_addr_bytes(*args)
semanage_node_get_addr_bytes = _semanage.semanage_node_get_addr_bytes

def semanage_node_set_addr(*args):
  return _semanage.semanage_node_set_addr(*args)
semanage_node_set_addr = _semanage.semanage_node_set_addr

def semanage_node_set_addr_bytes(*args):
  return _semanage.semanage_node_set_addr_bytes(*args)
semanage_node_set_addr_bytes = _semanage.semanage_node_set_addr_bytes

def semanage_node_get_mask(*args):
  return _semanage.semanage_node_get_mask(*args)
semanage_node_get_mask = _semanage.semanage_node_get_mask

def semanage_node_get_mask_bytes(*args):
  return _semanage.semanage_node_get_mask_bytes(*args)
semanage_node_get_mask_bytes = _semanage.semanage_node_get_mask_bytes

def semanage_node_set_mask(*args):
  return _semanage.semanage_node_set_mask(*args)
semanage_node_set_mask = _semanage.semanage_node_set_mask

def semanage_node_set_mask_bytes(*args):
  return _semanage.semanage_node_set_mask_bytes(*args)
semanage_node_set_mask_bytes = _semanage.semanage_node_set_mask_bytes

def semanage_node_get_proto(*args):
  return _semanage.semanage_node_get_proto(*args)
semanage_node_get_proto = _semanage.semanage_node_get_proto

def semanage_node_set_proto(*args):
  return _semanage.semanage_node_set_proto(*args)
semanage_node_set_proto = _semanage.semanage_node_set_proto

def semanage_node_get_proto_str(*args):
  return _semanage.semanage_node_get_proto_str(*args)
semanage_node_get_proto_str = _semanage.semanage_node_get_proto_str

def semanage_node_get_con(*args):
  return _semanage.semanage_node_get_con(*args)
semanage_node_get_con = _semanage.semanage_node_get_con

def semanage_node_set_con(*args):
  return _semanage.semanage_node_set_con(*args)
semanage_node_set_con = _semanage.semanage_node_set_con

def semanage_node_create(*args):
  return _semanage.semanage_node_create(*args)
semanage_node_create = _semanage.semanage_node_create

def semanage_node_clone(*args):
  return _semanage.semanage_node_clone(*args)
semanage_node_clone = _semanage.semanage_node_clone

def semanage_node_free(*args):
  return _semanage.semanage_node_free(*args)
semanage_node_free = _semanage.semanage_node_free

def semanage_node_modify_local(*args):
  return _semanage.semanage_node_modify_local(*args)
semanage_node_modify_local = _semanage.semanage_node_modify_local

def semanage_node_del_local(*args):
  return _semanage.semanage_node_del_local(*args)
semanage_node_del_local = _semanage.semanage_node_del_local

def semanage_node_query_local(*args):
  return _semanage.semanage_node_query_local(*args)
semanage_node_query_local = _semanage.semanage_node_query_local

def semanage_node_exists_local(*args):
  return _semanage.semanage_node_exists_local(*args)
semanage_node_exists_local = _semanage.semanage_node_exists_local

def semanage_node_count_local(*args):
  return _semanage.semanage_node_count_local(*args)
semanage_node_count_local = _semanage.semanage_node_count_local

def semanage_node_iterate_local(*args):
  return _semanage.semanage_node_iterate_local(*args)
semanage_node_iterate_local = _semanage.semanage_node_iterate_local

def semanage_node_list_local(*args):
  return _semanage.semanage_node_list_local(*args)
semanage_node_list_local = _semanage.semanage_node_list_local

def semanage_node_query(*args):
  return _semanage.semanage_node_query(*args)
semanage_node_query = _semanage.semanage_node_query

def semanage_node_exists(*args):
  return _semanage.semanage_node_exists(*args)
semanage_node_exists = _semanage.semanage_node_exists

def semanage_node_count(*args):
  return _semanage.semanage_node_count(*args)
semanage_node_count = _semanage.semanage_node_count

def semanage_node_iterate(*args):
  return _semanage.semanage_node_iterate(*args)
semanage_node_iterate = _semanage.semanage_node_iterate

def semanage_node_list(*args):
  return _semanage.semanage_node_list(*args)
semanage_node_list = _semanage.semanage_node_list


