.TH SEMODULE_PACKAGE "8" "Nov 2005" "Security Enhanced Linux"
.SH NAME
semodule_unpackage \- Extract policy module and file context file from an SELinux policy module package.

.SH SYNOPSIS
.B semodule_unpackage ppfile modfile [fcfile]
.br
.SH DESCRIPTION
.PP
semodule_unpackage is a tool used to extract SELinux policy module
file and file context file from an SELinux Policy Package.

.SH EXAMPLE
.nf
# Extract the httpd module file from httpd policy package.
$ semodule_unpackage httpd.pp httpd.mod httpd.fc
.fi

.SH SEE ALSO
.B semodule_package(8)
.SH AUTHORS
.nf
This manual page was written by Dan Walsh <dwalsh@redhat.com>.
The program was written by Stephen Smalley <stephen.smalley.work@gmail.com>
