.TH sandbox.conf "5" "Июнь 2010" "sandbox.conf" "Администрирование системы Linux"
.SH ИМЯ
sandbox.conf \- файл конфигурации пользователей для изолированной среды SELinux
.SH ОПИСАНИЕ
.PP
Если изолированная среда запускается с аргументом -C, она будет ограничена с помощью групп управления. Системный администратор может указать, как именно ограничить изолированную среду.

.PP
Весь текст после "#" игнорируется, как и пустые строки. Все аргументы должны быть разделены пробелами и иметь знаки равенства ("=").

.PP
Эти ключевые слова разрешены.

.RS
.TP
.B NAME
Имя группы управления изолированной средой.  По умолчанию: "sandbox".

.TP
.B CPUAFFINITY
Определяет, каким процессорам назначить изолированную среду. По умолчанию она назначается всем процессорам (ALL), но пользователи могут указать разделённый запятыми список с дефисами ("-"), чтобы представить диапазоны. Пример: 0-2,5

.TP
.B MEMUSAGE
Определяет, сколько памяти разрешается использовать изолированной среде. Значение по умолчанию: 80%. Пользователи могут указать либо процентное значение, либо значение в виде числа, за которым следует суффикс  K, M, G, для соответствующего обозначения килобайтов, мегабайтов или гигабайтов. Пример: 50% или 100M

.TP
.B CPUUSAGE
Процент использования ЦП, разрешённый для изолированной среды. По умолчанию: 80%. Укажите значение, за которым следует знак процента ("%"). Пример: 50%



.SH "СМОТРИТЕ ТАКЖЕ"
.TP
sandbox(8)
.PP

.SH АВТОРЫ
Эта страница руководства была написана
.I Thomas Liu <tliu@fedoraproject.org>.
Перевод на русский язык выполнила
.I Герасименко Олеся <gammaray@basealt.ru>.
