.TH SEUNSHARE "8" "Май 2010" "seunshare" "Команды пользователя"
.SH ИМЯ
seunshare \- выполнить cmd с другим домашним каталогом (homedir), временным каталогом (tmpdir) и/или контекстом SELinux 
.SH ОБЗОР
.B seunshare
[ -v ] [ -C ] [ -k ] [ -t tmpdir ] [ -h homedir ] [ -Z context ] -- executable [args]
.br
.SH ОПИСАНИЕ
.PP
Запустите исполняемый файл
.I executable
в указанном контексте, используя альтернативный домашний каталог и каталог /tmp. Команда seunshare отменяет общий доступ из пространства имён по умолчанию, затем монтирует указанные домашний каталог и временный каталог вместо домашнего каталога и временного каталога по умолчанию. После этого команда сообщает ядру, что следует выполнить приложение в указанном контексте SELinux.

.TP
\fB\-h homedir\fR
Альтернативный домашний каталог для использования приложением. Пользователь должен быть владельцем домашнего каталога.
.TP
\fB\-t\ tmpdir
Использовать альтернативный временный каталог для монтирования в /tmp. Пользователь должен быть владельцем временного каталога.
.TP
\fB\-C --capabilities\fR
Разрешить приложениям, исполняемым в пространстве имён, использовать средства для управления привилегиям. По умолчанию использование средств для управления привилегиями запрещено.
.TP
\fB\-k --kill\fR
Завершить все процессы с соответствующим уровнем MCS.
.TP
\fB\-Z\ context
Использовать альтернативный контекст SELinux при запуске исполняемого файла.
.TP
\fB\-v\fR
Подробный вывод
.SH "СМОТРИТЕ ТАКЖЕ"
.TP
runcon(1), sandbox(8), selinux(8)
.PP
.SH АВТОРЫ
Эта страница руководства была написана
.I Dan Walsh <dwalsh@redhat.com>
и
.I Thomas Liu <tliu@fedoraproject.org>.
Перевод на русский язык выполнила
.I Герасименко Олеся <gammaray@basealt.ru>.
