name: Check format

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: dnf install -y make clang-tools-extra
      - name: Check format
        run: make check-format
